In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
ds=pd.read_csv("data.csv")
ds

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
...,...,...,...,...,...,...
887,Ta,Tara,zest,"3,10,000",NaN,NaN
888,Tata Zest XM Diesel,Tata,2018,"2,60,000","27,000 kms",Diesel
889,Mahindra Quanto C8,Mahindra,2013,"3,90,000","40,000 kms",Diesel
890,Honda Amaze 1.2 E i VTEC,Honda,2014,"1,80,000",Petrol,NaN
891,Chevrolet Sail 1.2 LT ABS,Chevrolet,2014,"1,60,000",Petrol,NaN

In [3]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    object
 1   company     892 non-null    object
 2   year        892 non-null    object
 3   Price       892 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: object(6)
memory usage: 41.9+ KB

In [4]:
ds["name"].unique()

array(['Hyundai Santro Xing XO eRLX Euro III', 'Mahindra Jeep CL550 MDI',
       'Maruti Suzuki Alto 800 Vxi',
       'Hyundai Grand i10 Magna 1.2 Kappa VTVT',
       'Ford EcoSport Titanium 1.5L TDCi', 'Ford Figo', 'Hyundai Eon',
       'Ford EcoSport Ambiente 1.5L TDCi',
       'Maruti Suzuki Alto K10 VXi AMT', 'Skoda Fabia Classic 1.2 MPI',
       'Maruti Suzuki Stingray VXi', 'Hyundai Elite i20 Magna 1.2',
       'Mahindra Scorpio SLE BS IV', 'Audi A8', 'Audi Q7',
       'Mahindra Scorpio S10', 'Maruti Suzuki Alto 800',
       'Hyundai i20 Sportz 1.2', 'Maruti Suzuki Alto 800 Lx',
       'Maruti Suzuki Vitara Brezza ZDi', 'Maruti Suzuki Alto LX',
       'Mahindra Bolero DI', 'Maruti Suzuki Swift Dzire ZDi',
       'Mahindra Scorpio S10 4WD', 'Maruti Suzuki Swift Vdi BSIII',
       'Maruti Suzuki Wagon R VXi BS III',
       'Maruti Suzuki Wagon R VXi Minor',
       'Toyota Innova 2.0 G 8 STR BS IV', 'Renault Lodgy 85 PS RXL',
       'Skoda Yeti Ambition 2.0 TDI CR 4x2',
       'Maruti Suzuki Baleno Delta 1.2',
       'Renault Duster 110 PS RxZ Diesel Plus',
       'Renault Duster 85 PS RxE Diesel', 'Honda City 1.5 S MT',
       'Maruti Suzuki Dzire', 'Honda Amaze', 'Honda Amaze 1.5 SX i DTEC',
       'Honda City', 'Datsun Redi GO S', 'Maruti Suzuki SX4 ZXI MT',
       'Mitsubishi Pajero Sport Limited Edition',
       'Maruti Suzuki Swift VXi 1.2 ABS BS IV', 'Honda City ZX CVT',
       'Maruti Suzuki Wagon R LX BS IV', 'Tata Indigo eCS LS CR4 BS IV',
       'Volkswagen Polo Highline Exquisite P',
       'I want to sell my car Tata Zest', 'Chevrolet Spark LS 1.0',
       'Renault Duster 110PS Diesel RxZ', 'Mini Cooper S 1.6',
       'Skoda Fabia 1.2L Diesel Ambiente', 'Renault Duster',
       'Mahindra Scorpio S4', 'Mahindra Scorpio VLX 2WD BS IV',
       'Mahindra Quanto C8', 'Ford EcoSport', 'Honda Brio',
       'Volkswagen Vento Highline Plus 1.5 Diesel AT',
       'Hyundai i20 Magna', 'Toyota Corolla Altis Diesel D4DG',
       'Hyundai Verna Transform SX VTVT',
       'Toyota Corolla Altis Petrol Ltd', 'Honda City 1.5 EXi New',
       'Skoda Fabia 1.2L Diesel Elegance', 'BMW 3 Series 320i',
       'Maruti Suzuki A Star Lxi', 'Toyota Etios GD',
       'Ford Figo Diesel EXI Option',
       'Maruti Suzuki Swift Dzire VXi 1.2 BS IV',
       'Chevrolet Beat LT Diesel', 'BMW 7 Series 740Li Sedan',
       'Mahindra XUV500 W8 AWD 2013', 'Hyundai i10 Magna 1.2',
       'Hyundai Verna Fluidic New', 'Maruti Suzuki Swift VXi 1.2 BS IV',
       'Maruti Suzuki Ertiga ZXI Plus', 'Maruti Suzuki Ertiga Vxi',
       'Maruti Suzuki Ertiga VDi', 'Maruti Suzuki Alto LXi BS III',
       'Hyundai Grand i10 Asta 1.1 CRDi', 'Honda Amaze 1.2 S i VTEC',
       'Hyundai i20 Asta 1.4 CRDI 6 Speed', 'Ford Figo Diesel EXI',
       'Maruti Suzuki Eeco 5 STR WITH AC HTR', 'Maruti Suzuki Ertiga ZXi',
       'Maruti Suzuki Esteem LXi BS III', 'Maruti Suzuki Ritz VXI',
       'Maruti Suzuki Ritz LDi', 'Maruti Suzuki Dzire VDI',
       'Toyota Etios Liva G', 'Hyundai i20 Sportz 1.4 CRDI',
       'Chevrolet Spark', 'Nissan Micra XV', 'Maruti Suzuki Swift',
       'Honda Amaze 1.5 S i DTEC', 'Chevrolet Beat', 'Toyota Corolla',
       'Honda City 1.5 V MT', 'Ford EcoSport Trend 1.5L TDCi',
       'Hyundai i20 Asta 1.2', 'Tata Indica V2 eLS',
       'Maruti Suzuki Alto 800 Lxi', 'Hindustan Motors Ambassador',
       'Toyota Corolla Altis 1.8 GL', 'Toyota Corolla Altis 1.8 J',
       'Toyota Innova 2.5 GX BS IV 7 STR',
       'Volkswagen Jetta Highline TDI AT',
       'Volkswagen Polo Comfortline 1.2L P', 'Volkswagen Polo',
       'Mahindra Scorpio', 'Nissan Sunny', 'Hyundai Elite i20',
       'Renault Kwid', 'Mahindra Scorpio VLX Airbag',
       'Chevrolet Spark LT 1.0', 'Datsun Redi GO T O',
       'Maruti Suzuki Swift RS VDI', 'Fiat Punto Emotion 1.2',
       'Hyundai i10 Sportz 1.2', 'Chevrolet Beat LT Opt Diesel',
       'Chevrolet Beat LS Diesel', 'Tata Indigo CS',
       'Maruti Suzuki Swift VDi', 'Hyundai Eon Era Plus',
       'Mahindra XUV500', 'Ford Fiesta', 'Maruti Suzuki Wagon R',
       'Hyundai i20', 'Tata Indigo eCS LX TDI BS III',
       'Hyundai Fluidic Verna 1.6 CRDi SX',
       'Commercial , DZire LDI, 2016, for sale', 'Fiat Petra ELX 1.2 PS',
       'Hyundai Santro Xing XS', 'Maruti Suzuki Ciaz VXi Plus',
       'Maruti Suzuki Zen VX', 'Hyundai Creta 1.6 SX Plus Petrol',
       'Tata indigo ecs LX, 201', 'Mahindra Scorpio SLX',
       'Toyota Innova 2.5 G BS III 8 STR',
       'Maruti Suzuki Wagon R LXI BS IV', 'Tata Nano Cx BSIV',
       'Maruti Suzuki Alto Std BS IV', 'Maruti Suzuki Wagon R LXi BS III',
       'Maruti Suzuki Swift VXI BSIII',
       'Tata Sumo Victa EX 10 by 7 Str BSIII', 'MARUTI SUZUKI DESI',
       'Volkswagen Passat Diesel Comfortline AT',
       'Renault Scala RxL Diesel Travelogue',
       'Hyundai Grand i10 Sportz O 1.2 Kappa VTVT',
       'Hyundai i20 Active 1.2 SX', 'Mahindra Xylo E4',
       'Mahindra Jeep MM 550 XDB', 'Mahindra Bolero SLE BS IV',
       'Force Motors Force One LX ABS 7 STR', 'Maruti Suzuki SX4',
       'Toyota Etios', 'Honda City ZX VTEC',
       'Maruti Suzuki Wagon R LX BS III', 'Honda City VX O MT Diesel',
       'Mahindra Thar CRDe 4x4 AC',
       'Audi A4 1.8 TFSI Multitronic Premium Plus',
       'Mercedes Benz GLA Class 200 CDI Sport',
       'Land Rover Freelander 2 SE', 'Renault Kwid RXT',
       'Tata Aria Pleasure 4X2', 'Mercedes Benz B Class B180 Sports',
       'Datsun GO T O', 'Honda Jazz VX MT',
       'Hyundai i20 Active 1.4L SX O', 'Mini Cooper S',
       'Maruti Suzuki Ciaz ZXI Plus', 'Chevrolet Tavera Neo',
       'Hyundai Eon Sportz', 'Tata Sumo Gold Select Variant',
       'Maruti Suzuki Wagon R 1.0', 'Maruti Suzuki Esteem VXi BS III',
       'Chevrolet Enjoy 1.4 LS 8 STR', 'Maruti Suzuki Wagon R 1.0 VXi',
       'Nissan Terrano XL D Plus', 'Renault Duster 85 PS RxL Diesel',
       'Maruti Suzuki Dzire ZXI', 'Renault Kwid RXT Opt',
       'Maruti Suzuki Maruti 800 Std', 'Renault Kwid 1.0 RXT AMT',
       'Renault Scala RxL Diesel',
       'Hyundai Grand i10 Asta 1.2 Kappa VTVT O',
       'Chevrolet Beat LS Petrol', 'Hyundai Accent GLX', 'Yama',
       'Maruti Suzuki Swift LDi', 'Mahindra TUV300 T4 Plus',
       'Tata Indica V2 Xeta e GLE', 'Tata Indigo CS LS DiCOR',
       'Mahindra Scorpio VLX Special Edition BS III',
       'Tata Indica eV2 LS', 'Honda Accord',
       'Ford EcoSport Titanium 1.5 TDCi', 'Maruti Suzuki Ertiga',
       'Mahindra Scorpio 2.6 CRDe', 'Honda Mobilio',
       'Toyota Corolla Altis', 'Skoda Laura', 'Hyundai Verna Fluidic',
       'Maruti Suzuki Vitara Brezza', 'Tata Manza Aura Quadrajet',
       'Chevrolet Sail UVA Petrol LT ABS',
       'Hyundai Verna Fluidic 1.6 VTVT SX',
       'Audi A4 2.0 TDI 177bhp Premium', 'Hyundai Elantra SX',
       'Mahindra Scorpio VLX 4WD Airbag', 'Mahindra KUV100 K8 D 6 STR',
       'Hyundai Grand i10', 'Hyundai i10', 'Hyundai i20 Active',
       'Datsun Redi GO', 'Toyota Etios Liva', 'Hyundai Accent',
       'Hyundai Verna', 'Toyota Fortuner', 'Hyundai i10 Sportz',
       'Mahindra Bolero Power Plus SLE', 'selling car Ta',
       'Honda City 1.5 V MT Exclusive', 'Chevrolet Spark LT 1.0 Airbag',
       'Tata Indigo eCS VX CR4 BS IV', 'Tata Zest 90',
       'Skoda Rapid Elegance 1.6 TDI CR MT', 'Tata Vista Quadrajet VX',
       'Maruti Suzuki Alto K10 VXi AT', 'Maruti Suzuki Zen LXi BS III',
       'Maruti Suzuki Swift Dzire Tour LDi', 'Honda City ZX EXi',
       'Chevrolet Beat Diesel', 'Maruti Suzuki Swift Dzire car',
       'Hyundai Verna 1.4 VTVT', 'Toyota Innova 2.5 E MS 7 STR BS IV',
       'Maruti Suzuki Maruti 800 Std – Befo',
       'Hyundai Elite i20 Asta 1.4 CRDI',
       'Maruti Suzuki Swift Dzire Tour (Gat',
       'Maruti Suzuki Versa DX2 8 SEATER BSIII',
       'Tata Indigo LX TDI BS III',
       'Volkswagen Vento Konekt Diesel Highline',
       'Mercedes Benz C Class 200 CDI Classic', 'URJE',
       'Hyundai Santro Xing GLS', 'Maruti Suzuki Omni Limited Edition',
       'Hyundai Sonata Transform 2.4 GDi MT',
       'Hyundai Elite i20 Sportz 1.2', 'Honda Jazz S MT',
       'Hyundai Grand i10 Sportz 1.2 Kappa VTVT',
       'Maruti Suzuki Zen LXi BSII',
       'Mahindra Scorpio W Turbo 2.6DX 9 Seater',
       'Swift Dzire Tour 27 Dec 2016 Regis', 'Maruti Suzuki Alto K10 VXi',
       'Hyundai Grand i10 Asta 1.2 Kappa VTVT', 'Mahindra XUV500 W8',
       'Hyundai i20 Magna O 1.2', 'Renault Duster 85 PS RxL Explore LE',
       'Honda Brio V MT', 'Mahindra TUV300 T8',
       'Nissan X Trail Select Variant', 'Ford Ikon 1.3 CLXi NXt Finesse',
       'Toyota Fortuner 3.0 4x4 MT', 'Tata Manza ELAN Quadrajet',
       'Tata zest x', 'Mahindra xyl',
       'Mercedes Benz A Class A 180 Sport Petrol', 'Tata Indigo LS',
       'Hyundai i20 Magna 1.2', 'Used Commercial Maruti Omn',
       'Honda Amaze 1.5 E i DTEC', 'Hyundai Verna 1.6 EX VTVT',
       'BMW 5 Series 520d Sedan', 'Skoda Superb 1.8 TFSI AT',
       'Audi Q3 2.0 TDI quattro Premium', 'Mahindra Bolero DI BSII',
       'Maruti Suzuki Zen Estilo LXI Green CNG',
       'Ford Figo Duratorq Diesel Titanium 1.4',
       'Maruti Suzuki Wagon R VXI BS IV', 'Mahindra Logan Diesel 1.5 DLS',
       'Tata Nano GenX XMA', 'Honda City SV', 'Ford Figo Petrol LXI',
       'Hyundai i10 Magna 1.2 Kappa2', 'Toyota Corolla H2',
       'Maruti Suzuki Swift Dzire Tour VXi', 'Tata Indigo CS eLS BS IV',
       'Hyundai Xcent Base 1.1 CRDi', 'Hyundai Accent Executive Edition',
       'Tata Zest XE 75 PS Diesel', 'Maruti Suzuki Dzire LDI',
       'Tata Sumo Gold LX BS IV', 'Toyota Corolla Altis GL Petrol',
       'Maruti Suzuki Eeco 7 STR', 'Toyota Fortuner 3.0 4x2 MT',
       'Mahindra XUV500 W6', 'Tata Tigor Revotron XZ',
       'Maruti Suzuki 800', 'Honda Mobilio S i DTEC',
       'Hyundai Verna 1.6 CRDI E', 'Maruti Suzuki Omni Select Variant',
       'Tata Indica', 'Hyundai Santro Xing', 'Maruti Suzuki Zen Estilo',
       'Honda Brio VX AT', 'Maruti Suzuki Wagon R Select Variant',
       'Tata Nano Lx BSIV', 'Jaguar XE XE Portfolio',
       'Hyundai Xcent S 1.2', 'Hyundai Eon Magna Plus',
       'Maruti Suzuki Ritz GENUS VXI',
       'Hyundai Grand i10 Magna AT 1.2 Kappa VTVT',
       'Hyundai Eon D Lite Plus', 'Honda Amaze 1.2 VX i VTEC',
       'Maruti Suzuki Estilo VXi ABS BS IV',
       'Maruti Suzuki Vitara Brezza LDi O', 'Toyota Innova 2.0 V',
       'Hyundai Creta 1.6 SX Plus Petrol AT', 'Mahindra Scorpio Vlx BSIV',
       'Mitsubishi Lancer 1.8 LXi', 'Maruti Suzuki Maruti 800 AC',
       'Maruti Suzuki Alto 800 LXI CNG O', 'Ford Fiesta SXi 1.6 ABS',
       'Maruti Suzuki Ritz VDi', 'Maruti Suzuki Estilo LX BS IV',
       'Audi A6 2.0 TDI Premium', 'Maruti Suzuki Alto',
       'Maruti Suzuki Baleno Sigma 1.2', 'Hyundai Verna 1.6 SX VTVT AT',
       'Maruti Suzuki Swift GLAM', 'Hyundai Getz Prime 1.3 GVS',
       'Hyundai Santro', 'Hyundai Getz Prime 1.3 GLX',
       'Chevrolet Beat PS Diesel', 'Ford EcoSport Trend 1.5 Ti VCT',
       'Tata Indica V2 DLG', 'BMW X1 xDrive20d xLine',
       'Honda City 1.5 V AT', 'Tata Nano', 'Chevrolet Cruze LTZ AT',
       'Hyun', 'Maruti Suzuki Swift Dzire VDi', 'Mahindra XUV500 W10',
       'Maruti Suzuki Alto K10 LXi CNG', 'Hyundai Accent GLE',
       'Force Motors One SUV', 'Datsun Go Plus T O',
       'Chevrolet Spark 1.0 LT', 'Toyota Etios Liva GD',
       'Renault Duster 85PS Diesel RxL Optional with Nav',
       'Chevrolet Enjoy', 'BMW 5 Series 530i', 'Chevrolet Cruze LTZ',
       'Jeep Wrangler Unlimited 4x4 Diesel',
       'Hyundai Verna VGT CRDi SX ABS', 'Maruti Suzuki Omni',
       'Maruti Suzuki Celerio VDi', 'Tata Zest Quadrajet 1.3',
       'Tata Indigo CS eLX BS IV', 'Hyundai i10 Era',
       'Tata Indigo eCS LX CR4 BS IV', 'Tata Indigo Marina LS',
       'Commercial Chevrolet Sail Hatchback ca', 'Hyundai Xcent SX 1.2',
       'Tata Nano LX Special Edition', 'Commercial Car Ta',
       'Renault Duster 110 PS RxZ Diesel',
       'Maruti Suzuki Wagon R AX BSIV', 'Maruti Suzuki Alto K10 New',
       'tata Indica', 'Mahindra Xylo E8', 'Tata Manza Aqua Quadrajet',
       'Used bt new conditions ta', 'Renault Kwid 1.0', 'Sale tata',
       'Tata Venture EX 8 STR', 'Maruti Suzuki Swift Dzire Tour LXi',
       'Maruti Suzuki Alto LX BSII', 'Skoda Octavia Classic 1.9 TDI MT',
       'Maruti Suzuki Omni LPG BS IV', 'Tata Sumo Gold EX BS IV',
       'Tata indigo 2017 top model..', 'Hyundai Verna 1.6 CRDI SX',
       'Mahindra Scorpio SLX 2.6 Turbo 8 Str', 'Ford Ikon 1.6 Nxt',
       'Tata indigo', 'Toyota Innova 2.5 V 7 STR', 'Nissan Sunny XL',
       'Maruti Suzuki Swift VDi BS IV',
       'very good condition tata bolts are av', 'Toyota Innova 2.0 G4',
       'Sale Hyundai xcent commerc', 'Maruti Suzuki Swift VDi ABS',
       'Hyundai Elite i20 Asta 1.2', 'Volkswagen Polo Trendline 1.5L D',
       'Toyota Etios Liva Diesel', 'Maruti Suzuki Ciaz ZXi Plus RS',
       'Hyundai Elantra 1.8 S', 'Ford EcoSport Trend 1.5L Ti VCT',
       'Jaguar XF 2.2 Diesel Luxury',
       'Audi Q5 2.0 TDI quattro Premium Plus', 'BMW 3 Series 320d Sedan',
       'Maruti Suzuki Swift ZXi 1.2 BS IV', 'BMW X1 sDrive20d',
       'Maruti Suzuki S Cross Sigma 1.3', 'Maruti Suzuki Ertiga LDi',
       'Volkswagen Vento Comfortline Petrol', 'Mahindra KUV100',
       'Maruti Suzuki Swift Dzire Tour VDi', 'Mahindra Scorpio 2.6 SLX',
       'Maruti Suzuki Omni 8 STR BS III',
       'Volkswagen Jetta Comfortline 1.9 TDI AT', 'Volvo S80 Summum D4',
       'Toyota Corolla Altis VL AT Petrol',
       'Mitsubishi Pajero Sport 2.5 AT', 'Chevrolet Beat LT Petrol',
       'BMW X1', 'Mercedes Benz C Class C 220 CDI Avantgarde',
       'Volkswagen Vento Comfortline Diesel', 'Tata Indigo CS GLS',
       'Ford Figo Petrol Titanium', 'Honda City ZX GXi',
       'Maruti Suzuki Wagon R Duo Lxi', 'Maruti Suzuki Zen LX BSII',
       'Renault Duster RxL Petrol', 'Maruti Suzuki Baleno Zeta 1.2',
       'Honda WR V S MT Petrol', 'Renault Duster 110 PS RxL Diesel',
       'Mahindra Scorpio LX BS III',
       'Maruti Suzuki SX4 Celebration Diesel',
       'Audi A3 Cabriolet 40 TFSI',
       'I want to sell my commercial car due t',
       'Hyundai Santro AE GLS Audio',
       'i want sale my car.no emi....uber atta', 'Tata ZEST 6 month old',
       'Mahindra Xylo D2 BS IV', 'Hyundai Getz GLE',
       'Hyundai Creta 1.6 SX', 'Hyundai Santro Xing XL AT eRLX Euro III',
       'Hyundai Santro Xing XL eRLX Euro III',
       'Tata Indica V2 DLS BS III', 'Honda City 1.5 E MT',
       'Nissan Micra XL', 'Honda City 1.5 S Inspire',
       'Tata Indica eV2 eXeta eGLX', 'Maruti Suzuki Omni E 8 STR BS IV',
       'MARUTI SUZUKI ERTIGA F', 'Hyundai Verna 1.6 CRDI SX Plus AT',
       'Chevrolet Tavera LS B3 10 Seats BSII', 'Tata Tiago Revotron XM',
       'Tata Tiago Revotorq XZ', 'Tata Nexon', 'Tata',
       'Hindustan Motors Ambassador Classic Mark 4 – Befo',
       'Ford Fusion 1.4 TDCi Diesel',
       'Fiat Linea Emotion 1.4 L T Jet Petrol',
       'Ford Ikon 1.3 Flair Josh 100', 'Tata Indica V2 LS',
       'Mahindra Xylo D2', 'Hyundai Eon Magna',
       'Tata Sumo Grande MKII GX', 'Volkswagen Polo Highline1.2L P',
       'Tata Tiago Revotron XZ', 'Tata Indigo eCS',
       '2012 Tata Sumo Gold f', 'Mahindra Xylo E8 BS IV',
       'Well mentained Tata Sumo',
       'all paper updated tata indica v2 and u',
       'Maruti Ertiga showroom condition with',
       '7 SEATER MAHINDRA BOLERO IN VERY GOOD', '9 SEATER MAHINDRA BOL',
       'scratch less Tata I', 'Maruti Suzuki swift dzire for sale in',
       'Commercial Chevrolet beat for sale in',
       'urgent sell my Mahindra qu', 'Tata Sumo Gold FX BSIII',
       'sell my car Maruti Suzuki Swif',
       'Maruti Suzuki Swift Dzire good car fo', 'Hyunda',
       'Commercial Maruti Suzuki Alto Lxi 800', 'urgent sale Ta',
       'Maruti Suzuki Alto vxi t', 'tata', 'TATA INDI', 'Hyundai Creta',
       'Tata Bolt XM Petrol', 'Hyundai Venue', 'Maruti Suzuki Ritz',
       'Renault Lodgy', 'Hyundai i20 Asta',
       'Maruti Suzuki Swift Select Variant', 'Tata Indica V2 DLX BS III',
       'Mahindra Scorpio VLX 2.2 mHawk Airbag BSIV',
       'Toyota Innova 2.5 E 8 STR', 'Mahindra KUV100 K8 6 STR',
       'Datsun Go Plus', 'Ford Endeavor 4x4 Thunder Plus',
       'Tata Indica V2', 'Hyundai Santro Xing GL',
       'Toyota Innova 2.5 Z Diesel 7 Seater',
       'Any type car avaiabel hare...comercica', 'Maruti Suzuki Alto AX',
       'Mahindra Logan', 'Maruti Suzuki 800 Std BS III',
       'Chevrolet Sail 1.2 LS',
       'Volkswagen Vento Highline Plus 1.5 Diesel', 'Tata Manza',
       'Toyota Innova 2.0 G1 Petrol 8seater', 'Toyota Etios G',
       'Toyota Qualis', 'Mahindra Quanto C4', 'Maruti Suzuki Swift Dzire',
       'Hyundai i20 Select Variant', 'Honda City VX Petrol',
       'Hyundai Getz', 'Mercedes Benz C Class 200 K MT', 'Skoda Fabia',
       'Maruti Suzuki Alto 800 Select Variant',
       'Maruti Suzuki Ritz VXI ABS', 'tata zest 2017 f',
       'Tata Indica V2 DLE BS III', 'Ta', 'Tata Zest XM Diesel',
       'Honda Amaze 1.2 E i VTEC', 'Chevrolet Sail 1.2 LT ABS'],
      dtype=object)

In [5]:
ds["company"].unique()

array(['Hyundai', 'Mahindra', 'Maruti', 'Ford', 'Skoda', 'Audi', 'Toyota',
       'Renault', 'Honda', 'Datsun', 'Mitsubishi', 'Tata', 'Volkswagen',
       'I', 'Chevrolet', 'Mini', 'BMW', 'Nissan', 'Hindustan', 'Fiat',
       'Commercial', 'MARUTI', 'Force', 'Mercedes', 'Land', 'Yamaha',
       'selling', 'URJENT', 'Swift', 'Used', 'Jaguar', 'Jeep', 'tata',
       'Sale', 'very', 'Volvo', 'i', '2012', 'Well', 'all', '7', '9',
       'scratch', 'urgent', 'sell', 'TATA', 'Any', 'Tara'], dtype=object)

In [6]:
ds["year"].unique()

array(['2007', '2006', '2018', '2014', '2015', '2012', '2013', '2016',
       '2010', '2017', '2008', '2011', '2019', '2009', '2005', '2000',
       '...', '150k', 'TOUR', '2003', 'r 15', '2004', 'Zest', '/-Rs',
       'sale', '1995', 'ara)', '2002', 'SELL', '2001', 'tion', 'odel',
       '2 bs', 'arry', 'Eon', 'o...', 'ture', 'emi', 'car', 'able', 'no.',
       'd...', 'SALE', 'digo', 'sell', 'd Ex', 'n...', 'e...', 'D...',
       ', Ac', 'go .', 'k...', 'o c4', 'zire', 'cent', 'Sumo', 'cab',
       't xe', 'EV2', 'r...', 'zest'], dtype=object)

In [7]:
ds["Price"].unique()

array(['80,000', '4,25,000', 'Ask For Price', '3,25,000', '5,75,000',
       '1,75,000', '1,90,000', '8,30,000', '2,50,000', '1,82,000',
       '3,15,000', '4,15,000', '3,20,000', '10,00,000', '5,00,000',
       '3,50,000', '1,60,000', '3,10,000', '75,000', '1,00,000',
       '2,90,000', '95,000', '1,80,000', '3,85,000', '1,05,000',
       '6,50,000', '6,89,999', '4,48,000', '5,49,000', '5,01,000',
       '4,89,999', '2,80,000', '3,49,999', '2,84,999', '3,45,000',
       '4,99,999', '2,35,000', '2,49,999', '14,75,000', '3,95,000',
       '2,20,000', '1,70,000', '85,000', '2,00,000', '5,70,000',
       '1,10,000', '4,48,999', '18,91,111', '1,59,500', '3,44,999',
       '4,49,999', '8,65,000', '6,99,000', '3,75,000', '2,24,999',
       '12,00,000', '1,95,000', '3,51,000', '2,40,000', '90,000',
       '1,55,000', '6,00,000', '1,89,500', '2,10,000', '3,90,000',
       '1,35,000', '16,00,000', '7,01,000', '2,65,000', '5,25,000',
       '3,72,000', '6,35,000', '5,50,000', '4,85,000', '3,29,500',
       '2,51,111', '5,69,999', '69,999', '2,99,999', '3,99,999',
       '4,50,000', '2,70,000', '1,58,400', '1,79,000', '1,25,000',
       '2,99,000', '1,50,000', '2,75,000', '2,85,000', '3,40,000',
       '70,000', '2,89,999', '8,49,999', '7,49,999', '2,74,999',
       '9,84,999', '5,99,999', '2,44,999', '4,74,999', '2,45,000',
       '1,69,500', '3,70,000', '1,68,000', '1,45,000', '98,500',
       '2,09,000', '1,85,000', '9,00,000', '6,99,999', '1,99,999',
       '5,44,999', '1,99,000', '5,40,000', '49,000', '7,00,000', '55,000',
       '8,95,000', '3,55,000', '5,65,000', '3,65,000', '40,000',
       '4,00,000', '3,30,000', '5,80,000', '3,79,000', '2,19,000',
       '5,19,000', '7,30,000', '20,00,000', '21,00,000', '14,00,000',
       '3,11,000', '8,55,000', '5,35,000', '1,78,000', '3,00,000',
       '2,55,000', '5,49,999', '3,80,000', '57,000', '4,10,000',
       '2,25,000', '1,20,000', '59,000', '5,99,000', '6,75,000', '72,500',
       '6,10,000', '2,30,000', '5,20,000', '5,24,999', '4,24,999',
       '6,44,999', '5,84,999', '7,99,999', '4,44,999', '6,49,999',
       '9,44,999', '5,74,999', '3,74,999', '1,30,000', '4,01,000',
       '13,50,000', '1,74,999', '2,39,999', '99,999', '3,24,999',
       '10,74,999', '11,30,000', '1,49,000', '7,70,000', '30,000',
       '3,35,000', '3,99,000', '65,000', '1,69,999', '1,65,000',
       '5,60,000', '9,50,000', '7,15,000', '45,000', '9,40,000',
       '1,55,555', '15,00,000', '4,95,000', '8,00,000', '12,99,000',
       '5,30,000', '14,99,000', '32,000', '4,05,000', '7,60,000',
       '7,50,000', '4,19,000', '1,40,000', '15,40,000', '1,23,000',
       '4,98,000', '4,80,000', '4,88,000', '15,25,000', '5,48,900',
       '7,25,000', '99,000', '52,000', '28,00,000', '4,99,000',
       '3,81,000', '2,78,000', '6,90,000', '2,60,000', '90,001',
       '1,15,000', '15,99,000', '1,59,000', '51,999', '2,15,000',
       '35,000', '11,50,000', '2,69,000', '60,000', '4,30,000',
       '85,00,003', '4,01,919', '4,90,000', '4,24,000', '2,05,000',
       '5,49,900', '3,71,500', '4,35,000', '1,89,700', '3,89,700',
       '3,60,000', '2,95,000', '1,14,990', '10,65,000', '4,70,000',
       '48,000', '1,88,000', '4,65,000', '1,79,999', '21,90,000',
       '23,90,000', '10,75,000', '4,75,000', '10,25,000', '6,15,000',
       '19,00,000', '14,90,000', '15,10,000', '18,50,000', '7,90,000',
       '17,25,000', '12,25,000', '68,000', '9,70,000', '31,00,000',
       '8,99,000', '88,000', '53,000', '5,68,500', '71,000', '5,90,000',
       '7,95,000', '42,000', '1,89,000', '1,62,000', '35,999',
       '29,00,000', '39,999', '50,500', '5,10,000', '8,60,000',
       '5,00,001'], dtype=object)

In [8]:
ds["kms_driven"].unique()

array(['45,000 kms', '40 kms', '22,000 kms', '28,000 kms', '36,000 kms',
       '59,000 kms', '41,000 kms', '25,000 kms', '24,530 kms',
       '60,000 kms', '30,000 kms', '32,000 kms', '48,660 kms',
       '4,000 kms', '16,934 kms', '43,000 kms', '35,550 kms',
       '39,522 kms', '39,000 kms', '55,000 kms', '72,000 kms',
       '15,975 kms', '70,000 kms', '23,452 kms', '35,522 kms',
       '48,508 kms', '15,487 kms', '82,000 kms', '20,000 kms',
       '68,000 kms', '38,000 kms', '27,000 kms', '33,000 kms',
       '46,000 kms', '16,000 kms', '47,000 kms', '35,000 kms',
       '30,874 kms', '15,000 kms', '29,685 kms', '1,30,000 kms',
       '19,000 kms', nan, '54,000 kms', '13,000 kms', '38,200 kms',
       '50,000 kms', '13,500 kms', '3,600 kms', '45,863 kms',
       '60,500 kms', '12,500 kms', '18,000 kms', '13,349 kms',
       '29,000 kms', '44,000 kms', '42,000 kms', '14,000 kms',
       '49,000 kms', '36,200 kms', '51,000 kms', '1,04,000 kms',
       '33,333 kms', '33,600 kms', '5,600 kms', '7,500 kms', '26,000 kms',
       '24,330 kms', '65,480 kms', '28,028 kms', '2,00,000 kms',
       '99,000 kms', '2,800 kms', '21,000 kms', '11,000 kms',
       '66,000 kms', '3,000 kms', '7,000 kms', '38,500 kms', '37,200 kms',
       '43,200 kms', '24,800 kms', '45,872 kms', '40,000 kms',
       '11,400 kms', '97,200 kms', '52,000 kms', '31,000 kms',
       '1,75,430 kms', '37,000 kms', '65,000 kms', '3,350 kms',
       '75,000 kms', '62,000 kms', '73,000 kms', '2,200 kms',
       '54,870 kms', '34,580 kms', '97,000 kms', '60 kms', '80,200 kms',
       '3,200 kms', '0,000 kms', '5,000 kms', '588 kms', '71,200 kms',
       '1,75,400 kms', '9,300 kms', '56,758 kms', '10,000 kms',
       '56,450 kms', '56,000 kms', '32,700 kms', '9,000 kms', '73 kms',
       '1,60,000 kms', '84,000 kms', '58,559 kms', '57,000 kms',
       '1,70,000 kms', '80,000 kms', '6,821 kms', '23,000 kms',
       '34,000 kms', '1,800 kms', '4,00,000 kms', '48,000 kms',
       '90,000 kms', '12,000 kms', '69,900 kms', '1,66,000 kms',
       '122 kms', '0 kms', '24,000 kms', '36,469 kms', '7,800 kms',
       '24,695 kms', '15,141 kms', '59,910 kms', '1,00,000 kms',
       '4,500 kms', '1,29,000 kms', '300 kms', '1,31,000 kms',
       '1,11,111 kms', '59,466 kms', '25,500 kms', '44,005 kms',
       '2,110 kms', '43,222 kms', '1,00,200 kms', '65 kms',
       '1,40,000 kms', '1,03,553 kms', '58,000 kms', '1,20,000 kms',
       '49,800 kms', '100 kms', '81,876 kms', '6,020 kms', '55,700 kms',
       '18,500 kms', '1,80,000 kms', '53,000 kms', '35,500 kms',
       '22,134 kms', '1,000 kms', '8,500 kms', '87,000 kms', '6,000 kms',
       '15,574 kms', '8,000 kms', '55,800 kms', '56,400 kms',
       '72,160 kms', '11,500 kms', '1,33,000 kms', '2,000 kms',
       '88,000 kms', '65,422 kms', '1,17,000 kms', '1,50,000 kms',
       '10,750 kms', '6,800 kms', '5 kms', '9,800 kms', '57,923 kms',
       '30,201 kms', '6,200 kms', '37,518 kms', '24,652 kms', '383 kms',
       '95,000 kms', '3,528 kms', '52,500 kms', '47,900 kms',
       '52,800 kms', '1,95,000 kms', '48,008 kms', '48,247 kms',
       '9,400 kms', '64,000 kms', '2,137 kms', '10,544 kms', '49,500 kms',
       '1,47,000 kms', '90,001 kms', '48,006 kms', '74,000 kms',
       '85,000 kms', '29,500 kms', '39,700 kms', '67,000 kms',
       '19,336 kms', '60,105 kms', '45,933 kms', '1,02,563 kms',
       '28,600 kms', '41,800 kms', '1,16,000 kms', '42,590 kms',
       '7,400 kms', '54,500 kms', '76,000 kms', '00 kms', '11,523 kms',
       '38,600 kms', '95,500 kms', '37,458 kms', '85,960 kms',
       '12,516 kms', '30,600 kms', '2,550 kms', '62,500 kms',
       '69,000 kms', '28,400 kms', '68,485 kms', '3,500 kms',
       '85,455 kms', '63,000 kms', '1,600 kms', '77,000 kms',
       '26,500 kms', '2,875 kms', '13,900 kms', '1,500 kms', '2,450 kms',
       '1,625 kms', '33,400 kms', '60,123 kms', '38,900 kms',
       '1,37,495 kms', '91,200 kms', '1,46,000 kms', '1,00,800 kms',
       '2,100 kms', '2,500 kms', '1,32,000 kms', 'Petrol'], dtype=object)

In [9]:
ds["fuel_type"].unique()

array(['Petrol', 'Diesel', nan, 'LPG'], dtype=object)

In [10]:
ds["year"].unique()

array(['2007', '2006', '2018', '2014', '2015', '2012', '2013', '2016',
       '2010', '2017', '2008', '2011', '2019', '2009', '2005', '2000',
       '...', '150k', 'TOUR', '2003', 'r 15', '2004', 'Zest', '/-Rs',
       'sale', '1995', 'ara)', '2002', 'SELL', '2001', 'tion', 'odel',
       '2 bs', 'arry', 'Eon', 'o...', 'ture', 'emi', 'car', 'able', 'no.',
       'd...', 'SALE', 'digo', 'sell', 'd Ex', 'n...', 'e...', 'D...',
       ', Ac', 'go .', 'k...', 'o c4', 'zire', 'cent', 'Sumo', 'cab',
       't xe', 'EV2', 'r...', 'zest'], dtype=object)

In [11]:
ds["year"] = pd.to_numeric(ds["year"],errors='coerce')

In [12]:
ds["year"].unique()

array([2007., 2006., 2018., 2014., 2015., 2012., 2013., 2016., 2010.,
       2017., 2008., 2011., 2019., 2009., 2005., 2000.,   nan, 2003.,
       2004., 1995., 2002., 2001.])

In [13]:
ds.dropna(subset=["year"],inplace=True)

In [14]:
ds["year"].unique()

array([2007., 2006., 2018., 2014., 2015., 2012., 2013., 2016., 2010.,
       2017., 2008., 2011., 2019., 2009., 2005., 2000., 2003., 2004.,
       1995., 2002., 2001.])

In [15]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 842 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        842 non-null    object
 1   company     842 non-null    object
 2   year        842 non-null    float64
 3   Price       842 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: float64(1), object(5)
memory usage: 46.0+ KB

In [16]:
ds["Price"].unique()

array(['80,000', '4,25,000', 'Ask For Price', '3,25,000', '5,75,000',
       '1,75,000', '1,90,000', '8,30,000', '2,50,000', '1,82,000',
       '3,15,000', '4,15,000', '3,20,000', '10,00,000', '5,00,000',
       '3,50,000', '1,60,000', '3,10,000', '75,000', '1,00,000',
       '2,90,000', '95,000', '1,80,000', '3,85,000', '1,05,000',
       '6,50,000', '6,89,999', '4,48,000', '5,49,000', '5,01,000',
       '4,89,999', '2,80,000', '3,49,999', '2,84,999', '3,45,000',
       '4,99,999', '2,35,000', '2,49,999', '14,75,000', '3,95,000',
       '2,20,000', '1,70,000', '85,000', '2,00,000', '5,70,000',
       '1,10,000', '4,48,999', '18,91,111', '1,59,500', '3,44,999',
       '4,49,999', '8,65,000', '6,99,000', '3,75,000', '2,24,999',
       '12,00,000', '1,95,000', '3,51,000', '2,40,000', '90,000',
       '1,55,000', '6,00,000', '1,89,500', '2,10,000', '3,90,000',
       '1,35,000', '16,00,000', '7,01,000', '2,65,000', '5,25,000',
       '3,72,000', '6,35,000', '5,50,000', '4,85,000', '3,29,500',
       '2,51,111', '5,69,999', '69,999', '2,99,999', '3,99,999',
       '4,50,000', '2,70,000', '1,58,400', '1,79,000', '1,25,000',
       '2,99,000', '1,50,000', '2,75,000', '2,85,000', '3,40,000',
       '70,000', '2,89,999', '8,49,999', '7,49,999', '2,74,999',
       '9,84,999', '5,99,999', '2,44,999', '4,74,999', '2,45,000',
       '1,69,500', '3,70,000', '1,68,000', '1,45,000', '98,500',
       '2,09,000', '1,85,000', '9,00,000', '6,99,999', '1,99,999',
       '5,44,999', '1,99,000', '5,40,000', '49,000', '7,00,000', '55,000',
       '8,95,000', '3,55,000', '5,65,000', '3,65,000', '40,000',
       '4,00,000', '3,30,000', '5,80,000', '3,79,000', '2,19,000',
       '5,19,000', '7,30,000', '20,00,000', '21,00,000', '14,00,000',
       '3,11,000', '8,55,000', '5,35,000', '1,78,000', '3,00,000',
       '2,55,000', '5,49,999', '3,80,000', '57,000', '4,10,000',
       '2,25,000', '1,20,000', '59,000', '5,99,000', '6,75,000', '72,500',
       '6,10,000', '2,30,000', '5,20,000', '5,24,999', '4,24,999',
       '6,44,999', '5,84,999', '7,99,999', '4,44,999', '6,49,999',
       '9,44,999', '5,74,999', '3,74,999', '1,30,000', '4,01,000',
       '13,50,000', '1,74,999', '2,39,999', '99,999', '3,24,999',
       '10,74,999', '11,30,000', '1,49,000', '7,70,000', '30,000',
       '3,35,000', '3,99,000', '65,000', '1,69,999', '1,65,000',
       '5,60,000', '9,50,000', '7,15,000', '45,000', '9,40,000',
       '1,55,555', '15,00,000', '4,95,000', '8,00,000', '12,99,000',
       '5,30,000', '14,99,000', '32,000', '4,05,000', '7,60,000',
       '7,50,000', '4,19,000', '1,40,000', '15,40,000', '1,23,000',
       '4,98,000', '4,80,000', '4,88,000', '15,25,000', '5,48,900',
       '7,25,000', '99,000', '52,000', '28,00,000', '4,99,000',
       '3,81,000', '2,78,000', '6,90,000', '2,60,000', '90,001',
       '1,15,000', '15,99,000', '1,59,000', '51,999', '2,15,000',
       '35,000', '11,50,000', '2,69,000', '60,000', '4,30,000',
       '85,00,003', '4,01,919', '4,90,000', '4,24,000', '2,05,000',
       '5,49,900', '4,35,000', '1,89,700', '3,89,700', '3,60,000',
       '2,95,000', '1,14,990', '10,65,000', '4,70,000', '48,000',
       '1,88,000', '4,65,000', '1,79,999', '21,90,000', '23,90,000',
       '10,75,000', '4,75,000', '10,25,000', '6,15,000', '19,00,000',
       '14,90,000', '15,10,000', '18,50,000', '7,90,000', '17,25,000',
       '12,25,000', '68,000', '9,70,000', '31,00,000', '8,99,000',
       '88,000', '53,000', '5,68,500', '71,000', '5,90,000', '7,95,000',
       '42,000', '1,89,000', '1,62,000', '35,999', '29,00,000', '39,999',
       '50,500', '5,10,000', '8,60,000', '5,00,001'], dtype=object)

In [17]:
for i in ds.index:
    price = ds.loc[i,"Price"]
    price = price.replace(",","")
    ds.loc[i,"Price"] =price

In [18]:
ds["Price"].unique()

array(['80000', '425000', 'Ask For Price', '325000', '575000', '175000',
       '190000', '830000', '250000', '182000', '315000', '415000',
       '320000', '1000000', '500000', '350000', '160000', '310000',
       '75000', '100000', '290000', '95000', '180000', '385000', '105000',
       '650000', '689999', '448000', '549000', '501000', '489999',
       '280000', '349999', '284999', '345000', '499999', '235000',
       '249999', '1475000', '395000', '220000', '170000', '85000',
       '200000', '570000', '110000', '448999', '1891111', '159500',
       '344999', '449999', '865000', '699000', '375000', '224999',
       '1200000', '195000', '351000', '240000', '90000', '155000',
       '600000', '189500', '210000', '390000', '135000', '1600000',
       '701000', '265000', '525000', '372000', '635000', '550000',
       '485000', '329500', '251111', '569999', '69999', '299999',
       '399999', '450000', '270000', '158400', '179000', '125000',
       '299000', '150000', '275000', '285000', '340000', '70000',
       '289999', '849999', '749999', '274999', '984999', '599999',
       '244999', '474999', '245000', '169500', '370000', '168000',
       '145000', '98500', '209000', '185000', '900000', '699999',
       '199999', '544999', '199000', '540000', '49000', '700000', '55000',
       '895000', '355000', '565000', '365000', '40000', '400000',
       '330000', '580000', '379000', '219000', '519000', '730000',
       '2000000', '2100000', '1400000', '311000', '855000', '535000',
       '178000', '300000', '255000', '549999', '380000', '57000',
       '410000', '225000', '120000', '59000', '599000', '675000', '72500',
       '610000', '230000', '520000', '524999', '424999', '644999',
       '584999', '799999', '444999', '649999', '944999', '574999',
       '374999', '130000', '401000', '1350000', '174999', '239999',
       '99999', '324999', '1074999', '1130000', '149000', '770000',
       '30000', '335000', '399000', '65000', '169999', '165000', '560000',
       '950000', '715000', '45000', '940000', '155555', '1500000',
       '495000', '800000', '1299000', '530000', '1499000', '32000',
       '405000', '760000', '750000', '419000', '140000', '1540000',
       '123000', '498000', '480000', '488000', '1525000', '548900',
       '725000', '99000', '52000', '2800000', '499000', '381000',
       '278000', '690000', '260000', '90001', '115000', '1599000',
       '159000', '51999', '215000', '35000', '1150000', '269000', '60000',
       '430000', '8500003', '401919', '490000', '424000', '205000',
       '549900', '435000', '189700', '389700', '360000', '295000',
       '114990', '1065000', '470000', '48000', '188000', '465000',
       '179999', '2190000', '2390000', '1075000', '475000', '1025000',
       '615000', '1900000', '1490000', '1510000', '1850000', '790000',
       '1725000', '1225000', '68000', '970000', '3100000', '899000',
       '88000', '53000', '568500', '71000', '590000', '795000', '42000',
       '189000', '162000', '35999', '2900000', '39999', '50500', '510000',
       '860000', '500001'], dtype=object)

In [19]:
ds["Price"] = pd.to_numeric(ds["Price"],errors='coerce')

In [20]:
ds["Price"].unique()

array([  80000.,  425000.,      nan,  325000.,  575000.,  175000.,
        190000.,  830000.,  250000.,  182000.,  315000.,  415000.,
        320000., 1000000.,  500000.,  350000.,  160000.,  310000.,
         75000.,  100000.,  290000.,   95000.,  180000.,  385000.,
        105000.,  650000.,  689999.,  448000.,  549000.,  501000.,
        489999.,  280000.,  349999.,  284999.,  345000.,  499999.,
        235000.,  249999., 1475000.,  395000.,  220000.,  170000.,
         85000.,  200000.,  570000.,  110000.,  448999., 1891111.,
        159500.,  344999.,  449999.,  865000.,  699000.,  375000.,
        224999., 1200000.,  195000.,  351000.,  240000.,   90000.,
        155000.,  600000.,  189500.,  210000.,  390000.,  135000.,
       1600000.,  701000.,  265000.,  525000.,  372000.,  635000.,
        550000.,  485000.,  329500.,  251111.,  569999.,   69999.,
        299999.,  399999.,  450000.,  270000.,  158400.,  179000.,
        125000.,  299000.,  150000.,  275000.,  285000.,  340000.,
         70000.,  289999.,  849999.,  749999.,  274999.,  984999.,
        599999.,  244999.,  474999.,  245000.,  169500.,  370000.,
        168000.,  145000.,   98500.,  209000.,  185000.,  900000.,
        699999.,  199999.,  544999.,  199000.,  540000.,   49000.,
        700000.,   55000.,  895000.,  355000.,  565000.,  365000.,
         40000.,  400000.,  330000.,  580000.,  379000.,  219000.,
        519000.,  730000., 2000000., 2100000., 1400000.,  311000.,
        855000.,  535000.,  178000.,  300000.,  255000.,  549999.,
        380000.,   57000.,  410000.,  225000.,  120000.,   59000.,
        599000.,  675000.,   72500.,  610000.,  230000.,  520000.,
        524999.,  424999.,  644999.,  584999.,  799999.,  444999.,
        649999.,  944999.,  574999.,  374999.,  130000.,  401000.,
       1350000.,  174999.,  239999.,   99999.,  324999., 1074999.,
       1130000.,  149000.,  770000.,   30000.,  335000.,  399000.,
         65000.,  169999.,  165000.,  560000.,  950000.,  715000.,
         45000.,  940000.,  155555., 1500000.,  495000.,  800000.,
       1299000.,  530000., 1499000.,   32000.,  405000.,  760000.,
        750000.,  419000.,  140000., 1540000.,  123000.,  498000.,
        480000.,  488000., 1525000.,  548900.,  725000.,   99000.,
         52000., 2800000.,  499000.,  381000.,  278000.,  690000.,
        260000.,   90001.,  115000., 1599000.,  159000.,   51999.,
        215000.,   35000., 1150000.,  269000.,   60000.,  430000.,
       8500003.,  401919.,  490000.,  424000.,  205000.,  549900.,
        435000.,  189700.,  389700.,  360000.,  295000.,  114990.,
       1065000.,  470000.,   48000.,  188000.,  465000.,  179999.,
       2190000., 2390000., 1075000.,  475000., 1025000.,  615000.,
       1900000., 1490000., 1510000., 1850000.,  790000., 1725000.,
       1225000.,   68000.,  970000., 3100000.,  899000.,   88000.,
         53000.,  568500.,   71000.,  590000.,  795000.,   42000.,
        189000.,  162000.,   35999., 2900000.,   39999.,   50500.,
        510000.,  860000.,  500001.])

In [21]:
ds.dropna(subset=["Price"],inplace=True)
ds

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007.0,80000.0,"45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006.0,425000.0,40 kms,Diesel
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014.0,325000.0,"28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014.0,575000.0,"36,000 kms",Diesel
6,Ford Figo,Ford,2012.0,175000.0,"41,000 kms",Diesel
...,...,...,...,...,...,...
886,Toyota Corolla Altis,Toyota,2009.0,300000.0,"1,32,000 kms",Petrol
888,Tata Zest XM Diesel,Tata,2018.0,260000.0,"27,000 kms",Diesel
889,Mahindra Quanto C8,Mahindra,2013.0,390000.0,"40,000 kms",Diesel
890,Honda Amaze 1.2 E i VTEC,Honda,2014.0,180000.0,Petrol,NaN
891,Chevrolet Sail 1.2 LT ABS,Chevrolet,2014.0,160000.0,Petrol,NaN

In [22]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 819 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        819 non-null    object
 1   company     819 non-null    object
 2   year        819 non-null    float64
 3   Price       819 non-null    float64
 4   kms_driven  819 non-null    object
 5   fuel_type   816 non-null    object
dtypes: float64(2), object(4)
memory usage: 44.8+ KB

In [23]:
ds["kms_driven"].unique()

array(['45,000 kms', '40 kms', '28,000 kms', '36,000 kms', '41,000 kms',
       '25,000 kms', '24,530 kms', '60,000 kms', '30,000 kms',
       '32,000 kms', '48,660 kms', '4,000 kms', '16,934 kms',
       '43,000 kms', '35,550 kms', '39,522 kms', '39,000 kms',
       '55,000 kms', '72,000 kms', '15,975 kms', '70,000 kms',
       '23,452 kms', '35,522 kms', '48,508 kms', '15,487 kms',
       '82,000 kms', '20,000 kms', '68,000 kms', '38,000 kms',
       '27,000 kms', '33,000 kms', '46,000 kms', '16,000 kms',
       '47,000 kms', '35,000 kms', '30,874 kms', '15,000 kms',
       '29,685 kms', '1,30,000 kms', '19,000 kms', '54,000 kms',
       '13,000 kms', '38,200 kms', '22,000 kms', '50,000 kms',
       '13,500 kms', '3,600 kms', '45,863 kms', '60,500 kms',
       '12,500 kms', '18,000 kms', '13,349 kms', '29,000 kms',
       '44,000 kms', '42,000 kms', '14,000 kms', '49,000 kms',
       '36,200 kms', '51,000 kms', '1,04,000 kms', '33,333 kms',
       '33,600 kms', '5,600 kms', '7,500 kms', '26,000 kms', '24,330 kms',
       '65,480 kms', '2,00,000 kms', '59,000 kms', '99,000 kms',
       '2,800 kms', '21,000 kms', '11,000 kms', '66,000 kms', '3,000 kms',
       '7,000 kms', '38,500 kms', '37,200 kms', '43,200 kms',
       '24,800 kms', '45,872 kms', '40,000 kms', '11,400 kms',
       '97,200 kms', '52,000 kms', '31,000 kms', '1,75,430 kms',
       '37,000 kms', '65,000 kms', '3,350 kms', '75,000 kms',
       '62,000 kms', '73,000 kms', '2,200 kms', '54,870 kms',
       '34,580 kms', '97,000 kms', '60 kms', '80,200 kms', '3,200 kms',
       '0,000 kms', '5,000 kms', '588 kms', '71,200 kms', '1,75,400 kms',
       '9,300 kms', '56,758 kms', '10,000 kms', '56,450 kms',
       '56,000 kms', '32,700 kms', '9,000 kms', '73 kms', '1,60,000 kms',
       '58,559 kms', '57,000 kms', '1,70,000 kms', '80,000 kms',
       '6,821 kms', '23,000 kms', '34,000 kms', '1,800 kms',
       '4,00,000 kms', '48,000 kms', '90,000 kms', '12,000 kms',
       '69,900 kms', '1,66,000 kms', '122 kms', '0 kms', '36,469 kms',
       '7,800 kms', '24,695 kms', '15,141 kms', '59,910 kms',
       '1,00,000 kms', '4,500 kms', '1,29,000 kms', '300 kms',
       '1,31,000 kms', '1,11,111 kms', '59,466 kms', '25,500 kms',
       '44,005 kms', '2,110 kms', '43,222 kms', '1,00,200 kms', '65 kms',
       '1,40,000 kms', '1,03,553 kms', '58,000 kms', '1,20,000 kms',
       '49,800 kms', '100 kms', '81,876 kms', '6,020 kms', '55,700 kms',
       '18,500 kms', '53,000 kms', '35,500 kms', '22,134 kms',
       '1,000 kms', '8,500 kms', '87,000 kms', '6,000 kms', '8,000 kms',
       '55,800 kms', '56,400 kms', '72,160 kms', '11,500 kms',
       '1,33,000 kms', '2,000 kms', '88,000 kms', '65,422 kms',
       '1,17,000 kms', '1,50,000 kms', '10,750 kms', '6,800 kms',
       '9,800 kms', '57,923 kms', '30,201 kms', '6,200 kms', '37,518 kms',
       '24,652 kms', '383 kms', '95,000 kms', '3,528 kms', '52,500 kms',
       '47,900 kms', '52,800 kms', '1,95,000 kms', '48,008 kms',
       '48,247 kms', '9,400 kms', '64,000 kms', '2,137 kms', '10,544 kms',
       '1,47,000 kms', '90,001 kms', '48,006 kms', '74,000 kms',
       '85,000 kms', '29,500 kms', '39,700 kms', '67,000 kms',
       '19,336 kms', '60,105 kms', '45,933 kms', '1,02,563 kms',
       '28,600 kms', '41,800 kms', '1,16,000 kms', '42,590 kms',
       '7,400 kms', '54,500 kms', '76,000 kms', '00 kms', '11,523 kms',
       '38,600 kms', '95,500 kms', '37,458 kms', '85,960 kms',
       '12,516 kms', '30,600 kms', '2,550 kms', '62,500 kms',
       '69,000 kms', '28,400 kms', '68,485 kms', '3,500 kms',
       '85,455 kms', '63,000 kms', '1,600 kms', '77,000 kms',
       '26,500 kms', '2,875 kms', '13,900 kms', '1,500 kms', '2,450 kms',
       '1,625 kms', '33,400 kms', '60,123 kms', '1,37,495 kms',
       '91,200 kms', '1,46,000 kms', '1,00,800 kms', '2,100 kms',
       '2,500 kms', '1,32,000 kms', 'Petrol'], dtype=object)

In [25]:
ds["kms_driven"].unique()

ds["kms_driven"] = ds["kms_driven"].str.replace(",","") #remove ,
ds["kms_driven"] = ds["kms_driven"].str.replace(" kms","")# remove kms
ds["kms_driven"].unique()

ds["kms_driven"] = pd.to_numeric(ds["kms_driven"],errors='coerce') #convert data type

0       45000.0
1          40.0
3       28000.0
4       36000.0
6       41000.0
         ...
886    132000.0
888     27000.0
889     40000.0
890         NaN
891         NaN
Name: kms_driven, Length: 819, dtype: float64

In [28]:
ds.dropna(subset=["kms_driven"],inplace=True)

In [31]:
ds["kms_driven"]

0       45000.0
1          40.0
3       28000.0
4       36000.0
6       41000.0
         ...
883     50000.0
885     30000.0
886    132000.0
888     27000.0
889     40000.0
Name: kms_driven, Length: 817, dtype: float64

In [32]:
ds

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007.0,80000.0,45000.0,Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006.0,425000.0,40.0,Diesel
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014.0,325000.0,28000.0,Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014.0,575000.0,36000.0,Diesel
6,Ford Figo,Ford,2012.0,175000.0,41000.0,Diesel
...,...,...,...,...,...,...
883,Maruti Suzuki Ritz VXI ABS,Maruti,2011.0,270000.0,50000.0,Petrol
885,Tata Indica V2 DLE BS III,Tata,2009.0,110000.0,30000.0,Diesel
886,Toyota Corolla Altis,Toyota,2009.0,300000.0,132000.0,Petrol
888,Tata Zest XM Diesel,Tata,2018.0,260000.0,27000.0,Diesel
889,Mahindra Quanto C8,Mahindra,2013.0,390000.0,40000.0,Diesel

In [33]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 817 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        817 non-null    object
 1   company     817 non-null    object
 2   year        817 non-null    float64
 3   Price       817 non-null    float64
 4   kms_driven  817 non-null    float64
 5   fuel_type   816 non-null    object
dtypes: float64(3), object(3)
memory usage: 44.7+ KB

In [34]:
ds["name"].unique()

array(['Hyundai Santro Xing XO eRLX Euro III', 'Mahindra Jeep CL550 MDI',
       'Hyundai Grand i10 Magna 1.2 Kappa VTVT',
       'Ford EcoSport Titanium 1.5L TDCi', 'Ford Figo', 'Hyundai Eon',
       'Ford EcoSport Ambiente 1.5L TDCi',
       'Maruti Suzuki Alto K10 VXi AMT', 'Skoda Fabia Classic 1.2 MPI',
       'Maruti Suzuki Stingray VXi', 'Hyundai Elite i20 Magna 1.2',
       'Mahindra Scorpio SLE BS IV', 'Audi A8', 'Audi Q7',
       'Mahindra Scorpio S10', 'Maruti Suzuki Alto 800',
       'Maruti Suzuki Alto 800 Vxi', 'Hyundai i20 Sportz 1.2',
       'Maruti Suzuki Alto 800 Lx', 'Maruti Suzuki Vitara Brezza ZDi',
       'Maruti Suzuki Alto LX', 'Mahindra Bolero DI',
       'Maruti Suzuki Swift Dzire ZDi', 'Mahindra Scorpio S10 4WD',
       'Maruti Suzuki Swift Vdi BSIII',
       'Maruti Suzuki Wagon R VXi BS III',
       'Maruti Suzuki Wagon R VXi Minor',
       'Toyota Innova 2.0 G 8 STR BS IV', 'Renault Lodgy 85 PS RXL',
       'Skoda Yeti Ambition 2.0 TDI CR 4x2',
       'Maruti Suzuki Baleno Delta 1.2',
       'Renault Duster 110 PS RxZ Diesel Plus',
       'Renault Duster 85 PS RxE Diesel', 'Honda City 1.5 S MT',
       'Maruti Suzuki Dzire', 'Honda Amaze', 'Honda Amaze 1.5 SX i DTEC',
       'Honda City', 'Datsun Redi GO S', 'Maruti Suzuki SX4 ZXI MT',
       'Mitsubishi Pajero Sport Limited Edition',
       'Maruti Suzuki Swift VXi 1.2 ABS BS IV', 'Honda City ZX CVT',
       'Maruti Suzuki Wagon R LX BS IV', 'Tata Indigo eCS LS CR4 BS IV',
       'Volkswagen Polo Highline Exquisite P', 'Chevrolet Spark LS 1.0',
       'Renault Duster 110PS Diesel RxZ', 'Mini Cooper S 1.6',
       'Skoda Fabia 1.2L Diesel Ambiente', 'Renault Duster',
       'Mahindra Scorpio S4', 'Mahindra Scorpio VLX 2WD BS IV',
       'Mahindra Quanto C8', 'Ford EcoSport', 'Honda Brio',
       'Volkswagen Vento Highline Plus 1.5 Diesel AT',
       'Hyundai i20 Magna', 'Toyota Corolla Altis Diesel D4DG',
       'Hyundai Verna Transform SX VTVT',
       'Toyota Corolla Altis Petrol Ltd', 'Honda City 1.5 EXi New',
       'Skoda Fabia 1.2L Diesel Elegance', 'BMW 3 Series 320i',
       'Maruti Suzuki A Star Lxi', 'Toyota Etios GD',
       'Ford Figo Diesel EXI Option',
       'Maruti Suzuki Swift Dzire VXi 1.2 BS IV',
       'Chevrolet Beat LT Diesel', 'BMW 7 Series 740Li Sedan',
       'Mahindra XUV500 W8 AWD 2013', 'Hyundai i10 Magna 1.2',
       'Hyundai Verna Fluidic New', 'Maruti Suzuki Swift VXi 1.2 BS IV',
       'Maruti Suzuki Ertiga ZXI Plus', 'Maruti Suzuki Ertiga Vxi',
       'Maruti Suzuki Ertiga VDi', 'Maruti Suzuki Alto LXi BS III',
       'Hyundai Grand i10 Asta 1.1 CRDi', 'Honda Amaze 1.2 S i VTEC',
       'Hyundai i20 Asta 1.4 CRDI 6 Speed', 'Ford Figo Diesel EXI',
       'Maruti Suzuki Eeco 5 STR WITH AC HTR', 'Maruti Suzuki Ertiga ZXi',
       'Maruti Suzuki Esteem LXi BS III', 'Maruti Suzuki Ritz VXI',
       'Maruti Suzuki Ritz LDi', 'Maruti Suzuki Dzire VDI',
       'Toyota Etios Liva G', 'Hyundai i20 Sportz 1.4 CRDI',
       'Chevrolet Spark', 'Nissan Micra XV', 'Maruti Suzuki Swift',
       'Honda Amaze 1.5 S i DTEC', 'Chevrolet Beat', 'Toyota Corolla',
       'Honda City 1.5 V MT', 'Ford EcoSport Trend 1.5L TDCi',
       'Hyundai i20 Asta 1.2', 'Tata Indica V2 eLS',
       'Hindustan Motors Ambassador', 'Toyota Corolla Altis 1.8 GL',
       'Toyota Corolla Altis 1.8 J', 'Toyota Innova 2.5 GX BS IV 7 STR',
       'Volkswagen Jetta Highline TDI AT',
       'Volkswagen Polo Comfortline 1.2L P', 'Volkswagen Polo',
       'Mahindra Scorpio', 'Nissan Sunny', 'Hyundai Elite i20',
       'Renault Kwid', 'Mahindra Scorpio VLX Airbag',
       'Maruti Suzuki Alto 800 Lxi', 'Chevrolet Spark LT 1.0',
       'Datsun Redi GO T O', 'Maruti Suzuki Swift RS VDI',
       'Fiat Punto Emotion 1.2', 'Hyundai i10 Sportz 1.2',
       'Chevrolet Beat LT Opt Diesel', 'Chevrolet Beat LS Diesel',
       'Tata Indigo CS', 'Maruti Suzuki Swift VDi',
       'Hyundai Eon Era Plus', 'Mahindra XUV500', 'Ford Fiesta',
       'Maruti Suzuki Wagon R', 'Hyundai i20',
       'Tata Indigo eCS LX TDI BS III',
       'Hyundai Fluidic Verna 1.6 CRDi SX', 'Fiat Petra ELX 1.2 PS',
       'Hyundai Santro Xing XS', 'Maruti Suzuki Ciaz VXi Plus',
       'Maruti Suzuki Zen VX', 'Hyundai Creta 1.6 SX Plus Petrol',
       'Mahindra Scorpio SLX', 'Toyota Innova 2.5 G BS III 8 STR',
       'Maruti Suzuki Wagon R LXI BS IV', 'Tata Nano Cx BSIV',
       'Maruti Suzuki Alto Std BS IV', 'Maruti Suzuki Wagon R LXi BS III',
       'Maruti Suzuki Swift VXI BSIII',
       'Tata Sumo Victa EX 10 by 7 Str BSIII',
       'Volkswagen Passat Diesel Comfortline AT',
       'Renault Scala RxL Diesel Travelogue',
       'Hyundai Grand i10 Sportz O 1.2 Kappa VTVT',
       'Hyundai i20 Active 1.2 SX', 'Mahindra Xylo E4',
       'Mahindra Jeep MM 550 XDB', 'Mahindra Bolero SLE BS IV',
       'Force Motors Force One LX ABS 7 STR', 'Maruti Suzuki SX4',
       'Toyota Etios', 'Honda City ZX VTEC',
       'Maruti Suzuki Wagon R LX BS III', 'Honda City VX O MT Diesel',
       'Mahindra Thar CRDe 4x4 AC',
       'Audi A4 1.8 TFSI Multitronic Premium Plus',
       'Mercedes Benz GLA Class 200 CDI Sport',
       'Land Rover Freelander 2 SE', 'Renault Kwid RXT',
       'Tata Aria Pleasure 4X2', 'Mercedes Benz B Class B180 Sports',
       'Datsun GO T O', 'Honda Jazz VX MT',
       'Hyundai i20 Active 1.4L SX O', 'Mini Cooper S',
       'Maruti Suzuki Ciaz ZXI Plus', 'Chevrolet Tavera Neo',
       'Hyundai Eon Sportz', 'Tata Sumo Gold Select Variant',
       'Maruti Suzuki Wagon R 1.0', 'Maruti Suzuki Esteem VXi BS III',
       'Chevrolet Enjoy 1.4 LS 8 STR', 'Maruti Suzuki Wagon R 1.0 VXi',
       'Nissan Terrano XL D Plus', 'Renault Duster 85 PS RxL Diesel',
       'Maruti Suzuki Dzire ZXI', 'Renault Kwid RXT Opt',
       'Maruti Suzuki Maruti 800 Std', 'Renault Kwid 1.0 RXT AMT',
       'Renault Scala RxL Diesel',
       'Hyundai Grand i10 Asta 1.2 Kappa VTVT O',
       'Chevrolet Beat LS Petrol', 'Hyundai Accent GLX',
       'Mahindra TUV300 T4 Plus', 'Tata Indica V2 Xeta e GLE',
       'Tata Indigo CS LS DiCOR',
       'Mahindra Scorpio VLX Special Edition BS III', 'Honda Accord',
       'Ford EcoSport Titanium 1.5 TDCi', 'Maruti Suzuki Ertiga',
       'Mahindra Scorpio 2.6 CRDe', 'Honda Mobilio',
       'Toyota Corolla Altis', 'Skoda Laura', 'Hyundai Verna Fluidic',
       'Maruti Suzuki Vitara Brezza', 'Tata Manza Aura Quadrajet',
       'Chevrolet Sail UVA Petrol LT ABS',
       'Hyundai Verna Fluidic 1.6 VTVT SX',
       'Audi A4 2.0 TDI 177bhp Premium', 'Hyundai Elantra SX',
       'Mahindra Scorpio VLX 4WD Airbag', 'Mahindra KUV100 K8 D 6 STR',
       'Hyundai Grand i10', 'Hyundai i10', 'Hyundai i20 Active',
       'Datsun Redi GO', 'Toyota Etios Liva', 'Hyundai Accent',
       'Hyundai Verna', 'Toyota Fortuner', 'Hyundai i10 Sportz',
       'Mahindra Bolero Power Plus SLE', 'Honda City 1.5 V MT Exclusive',
       'Chevrolet Spark LT 1.0 Airbag', 'Tata Indigo eCS VX CR4 BS IV',
       'Skoda Rapid Elegance 1.6 TDI CR MT', 'Tata Vista Quadrajet VX',
       'Maruti Suzuki Alto K10 VXi AT', 'Maruti Suzuki Zen LXi BS III',
       'Maruti Suzuki Swift Dzire Tour LDi', 'Honda City ZX EXi',
       'Chevrolet Beat Diesel', 'Hyundai Verna 1.4 VTVT',
       'Toyota Innova 2.5 E MS 7 STR BS IV',
       'Maruti Suzuki Maruti 800 Std – Befo',
       'Hyundai Elite i20 Asta 1.4 CRDI',
       'Maruti Suzuki Versa DX2 8 SEATER BSIII',
       'Tata Indigo LX TDI BS III',
       'Volkswagen Vento Konekt Diesel Highline',
       'Mercedes Benz C Class 200 CDI Classic', 'Hyundai Santro Xing GLS',
       'Maruti Suzuki Omni Limited Edition',
       'Hyundai Sonata Transform 2.4 GDi MT',
       'Hyundai Elite i20 Sportz 1.2', 'Honda Jazz S MT',
       'Hyundai Grand i10 Sportz 1.2 Kappa VTVT',
       'Maruti Suzuki Zen LXi BSII',
       'Mahindra Scorpio W Turbo 2.6DX 9 Seater',
       'Maruti Suzuki Alto K10 VXi',
       'Hyundai Grand i10 Asta 1.2 Kappa VTVT', 'Mahindra XUV500 W8',
       'Hyundai i20 Magna O 1.2', 'Renault Duster 85 PS RxL Explore LE',
       'Honda Brio V MT', 'Mahindra TUV300 T8',
       'Nissan X Trail Select Variant', 'Ford Ikon 1.3 CLXi NXt Finesse',
       'Toyota Fortuner 3.0 4x4 MT', 'Tata Manza ELAN Quadrajet',
       'Mercedes Benz A Class A 180 Sport Petrol', 'Tata Indigo LS',
       'Hyundai i20 Magna 1.2', 'Honda Amaze 1.5 E i DTEC',
       'Hyundai Verna 1.6 EX VTVT', 'BMW 5 Series 520d Sedan',
       'Skoda Superb 1.8 TFSI AT', 'Audi Q3 2.0 TDI quattro Premium',
       'Mahindra Bolero DI BSII',
       'Ford Figo Duratorq Diesel Titanium 1.4',
       'Maruti Suzuki Wagon R VXI BS IV', 'Mahindra Logan Diesel 1.5 DLS',
       'Tata Nano GenX XMA', 'Honda City SV', 'Ford Figo Petrol LXI',
       'Hyundai i10 Magna 1.2 Kappa2', 'Toyota Corolla H2',
       'Maruti Suzuki Swift Dzire Tour VXi', 'Tata Indigo CS eLS BS IV',
       'Hyundai Xcent Base 1.1 CRDi', 'Hyundai Accent Executive Edition',
       'Tata Zest XE 75 PS Diesel', 'Maruti Suzuki Dzire LDI',
       'Tata Sumo Gold LX BS IV', 'Toyota Corolla Altis GL Petrol',
       'Maruti Suzuki Eeco 7 STR', 'Toyota Fortuner 3.0 4x2 MT',
       'Mahindra XUV500 W6', 'Tata Tigor Revotron XZ',
       'Maruti Suzuki 800', 'Honda Mobilio S i DTEC',
       'Hyundai Verna 1.6 CRDI E', 'Maruti Suzuki Omni Select Variant',
       'Tata Indica', 'Hyundai Santro Xing', 'Maruti Suzuki Zen Estilo',
       'Honda Brio VX AT', 'Maruti Suzuki Zen Estilo LXI Green CNG',
       'Maruti Suzuki Wagon R Select Variant', 'Tata Nano Lx BSIV',
       'Jaguar XE XE Portfolio', 'Hyundai Eon Magna Plus',
       'Maruti Suzuki Ritz GENUS VXI',
       'Hyundai Grand i10 Magna AT 1.2 Kappa VTVT',
       'Hyundai Eon D Lite Plus', 'Honda Amaze 1.2 VX i VTEC',
       'Maruti Suzuki Estilo VXi ABS BS IV',
       'Maruti Suzuki Vitara Brezza LDi O',
       'Hyundai Creta 1.6 SX Plus Petrol AT', 'Mahindra Scorpio Vlx BSIV',
       'Mitsubishi Lancer 1.8 LXi', 'Maruti Suzuki Maruti 800 AC',
       'Maruti Suzuki Alto 800 LXI CNG O', 'Ford Fiesta SXi 1.6 ABS',
       'Maruti Suzuki Ritz VDi', 'Maruti Suzuki Estilo LX BS IV',
       'Audi A6 2.0 TDI Premium', 'Maruti Suzuki Alto',
       'Maruti Suzuki Baleno Sigma 1.2', 'Hyundai Verna 1.6 SX VTVT AT',
       'Maruti Suzuki Swift GLAM', 'Hyundai Getz Prime 1.3 GVS',
       'Hyundai Santro', 'Hyundai Getz Prime 1.3 GLX',
       'Chevrolet Beat PS Diesel', 'Ford EcoSport Trend 1.5 Ti VCT',
       'Tata Indica V2 DLG', 'BMW X1 xDrive20d xLine',
       'Honda City 1.5 V AT', 'Tata Nano', 'Chevrolet Cruze LTZ AT',
       'Maruti Suzuki Swift Dzire VDi', 'Mahindra XUV500 W10',
       'Maruti Suzuki Alto K10 LXi CNG', 'Hyundai Accent GLE',
       'Force Motors One SUV', 'Chevrolet Spark 1.0 LT',
       'Toyota Etios Liva GD',
       'Renault Duster 85PS Diesel RxL Optional with Nav',
       'Chevrolet Enjoy', 'BMW 5 Series 530i', 'Chevrolet Cruze LTZ',
       'Jeep Wrangler Unlimited 4x4 Diesel',
       'Hyundai Verna VGT CRDi SX ABS', 'Maruti Suzuki Omni',
       'Maruti Suzuki Celerio VDi', 'Tata Zest Quadrajet 1.3',
       'Tata Indigo CS eLX BS IV', 'Hyundai i10 Era',
       'Tata Indigo eCS LX CR4 BS IV', 'Tata Indigo Marina LS',
       'Hyundai Xcent SX 1.2', 'Tata Nano LX Special Edition',
       'Renault Duster 110 PS RxZ Diesel',
       'Maruti Suzuki Wagon R AX BSIV', 'Maruti Suzuki Alto K10 New',
       'Mahindra Xylo E8', 'Tata Manza Aqua Quadrajet',
       'Renault Kwid 1.0', 'Tata Venture EX 8 STR',
       'Maruti Suzuki Swift Dzire Tour LXi',
       'Skoda Octavia Classic 1.9 TDI MT', 'Maruti Suzuki Omni LPG BS IV',
       'Tata Sumo Gold EX BS IV', 'Hyundai Verna 1.6 CRDI SX',
       'Mahindra Scorpio SLX 2.6 Turbo 8 Str', 'Ford Ikon 1.6 Nxt',
       'Toyota Innova 2.5 V 7 STR', 'Nissan Sunny XL',
       'Maruti Suzuki Swift VDi BS IV', 'Toyota Innova 2.0 G4',
       'Maruti Suzuki Swift VDi ABS', 'Hyundai Elite i20 Asta 1.2',
       'Volkswagen Polo Trendline 1.5L D', 'Toyota Etios Liva Diesel',
       'Maruti Suzuki Ciaz ZXi Plus RS', 'Hyundai Elantra 1.8 S',
       'Ford EcoSport Trend 1.5L Ti VCT', 'Tata Indica eV2 LS',
       'Jaguar XF 2.2 Diesel Luxury',
       'Audi Q5 2.0 TDI quattro Premium Plus', 'BMW 3 Series 320d Sedan',
       'Maruti Suzuki Swift ZXi 1.2 BS IV', 'BMW X1 sDrive20d',
       'Maruti Suzuki S Cross Sigma 1.3', 'Maruti Suzuki Ertiga LDi',
       'Volkswagen Vento Comfortline Petrol', 'Mahindra KUV100',
       'Maruti Suzuki Swift Dzire Tour VDi', 'Mahindra Scorpio 2.6 SLX',
       'Maruti Suzuki Omni 8 STR BS III',
       'Volkswagen Jetta Comfortline 1.9 TDI AT', 'Volvo S80 Summum D4',
       'Toyota Corolla Altis VL AT Petrol',
       'Mitsubishi Pajero Sport 2.5 AT', 'Chevrolet Beat LT Petrol',
       'BMW X1', 'Mercedes Benz C Class C 220 CDI Avantgarde',
       'Volkswagen Vento Comfortline Diesel', 'Tata Indigo CS GLS',
       'Ford Figo Petrol Titanium', 'Honda City ZX GXi',
       'Maruti Suzuki Wagon R Duo Lxi', 'Maruti Suzuki Zen LX BSII',
       'Renault Duster RxL Petrol', 'Maruti Suzuki Baleno Zeta 1.2',
       'Honda WR V S MT Petrol', 'Renault Duster 110 PS RxL Diesel',
       'Mahindra Scorpio LX BS III',
       'Maruti Suzuki SX4 Celebration Diesel',
       'Audi A3 Cabriolet 40 TFSI', 'Hyundai Santro AE GLS Audio',
       'Mahindra Xylo D2 BS IV', 'Hyundai Getz GLE',
       'Hyundai Creta 1.6 SX', 'Hyundai Santro Xing XL AT eRLX Euro III',
       'Hyundai Santro Xing XL eRLX Euro III',
       'Tata Indica V2 DLS BS III', 'Honda City 1.5 E MT',
       'Nissan Micra XL', 'Honda City 1.5 S Inspire',
       'Tata Indica eV2 eXeta eGLX', 'Maruti Suzuki Omni E 8 STR BS IV',
       'Maruti Suzuki Swift LDi', 'Hyundai Verna 1.6 CRDI SX Plus AT',
       'Chevrolet Tavera LS B3 10 Seats BSII', 'Tata Tiago Revotron XM',
       'Tata Tiago Revotorq XZ',
       'Hindustan Motors Ambassador Classic Mark 4 – Befo',
       'Ford Fusion 1.4 TDCi Diesel',
       'Fiat Linea Emotion 1.4 L T Jet Petrol',
       'Ford Ikon 1.3 Flair Josh 100', 'Tata Indica V2 LS',
       'Mahindra Xylo D2', 'Hyundai Eon Magna',
       'Tata Sumo Grande MKII GX', 'Volkswagen Polo Highline1.2L P',
       'Tata Tiago Revotron XZ', 'Tata Indigo eCS',
       'Mahindra Xylo E8 BS IV', 'Tata Sumo Gold FX BSIII',
       'Hyundai Creta', 'Tata Bolt XM Petrol', 'Maruti Suzuki Ritz',
       'Hyundai i20 Asta', 'Maruti Suzuki Swift Select Variant',
       'Tata Indica V2 DLX BS III',
       'Mahindra Scorpio VLX 2.2 mHawk Airbag BSIV',
       'Toyota Innova 2.5 E 8 STR', 'Mahindra KUV100 K8 6 STR',
       'Datsun Go Plus', 'Ford Endeavor 4x4 Thunder Plus',
       'Tata Indica V2', 'Hyundai Santro Xing GL',
       'Toyota Innova 2.5 Z Diesel 7 Seater', 'Maruti Suzuki Alto AX',
       'Mahindra Logan', 'Maruti Suzuki 800 Std BS III',
       'Chevrolet Sail 1.2 LS', 'Tata Manza', 'Toyota Etios G',
       'Toyota Qualis', 'Mahindra Quanto C4', 'Maruti Suzuki Swift Dzire',
       'Hyundai i20 Select Variant', 'Honda City VX Petrol',
       'Hyundai Getz', 'Mercedes Benz C Class 200 K MT', 'Skoda Fabia',
       'Maruti Suzuki Ritz VXI ABS', 'Tata Indica V2 DLE BS III',
       'Tata Zest XM Diesel'], dtype=object)

In [35]:
ds["company"].unique()

array(['Hyundai', 'Mahindra', 'Ford', 'Maruti', 'Skoda', 'Audi', 'Toyota',
       'Renault', 'Honda', 'Datsun', 'Mitsubishi', 'Tata', 'Volkswagen',
       'Chevrolet', 'Mini', 'BMW', 'Nissan', 'Hindustan', 'Fiat', 'Force',
       'Mercedes', 'Land', 'Jaguar', 'Jeep', 'Volvo'], dtype=object)

In [41]:
for i in ds.index:
    company  = ds.loc[i,"company"]
    name = ds.loc[i,"name"]
    name = name.replace(company,"")
    ds.loc[i,"name"] = name
ds["name"] = ds["name"].str.strip()
ds["name"].unique()

array(['Santro Xing XO eRLX Euro III', 'Jeep CL550 MDI',
       'Grand i10 Magna 1.2 Kappa VTVT', 'EcoSport Titanium 1.5L TDCi',
       'Figo', 'Eon', 'EcoSport Ambiente 1.5L TDCi',
       'Suzuki Alto K10 VXi AMT', 'Fabia Classic 1.2 MPI',
       'Suzuki Stingray VXi', 'Elite i20 Magna 1.2', 'Scorpio SLE BS IV',
       'A8', 'Q7', 'Scorpio S10', 'Suzuki Alto 800',
       'Suzuki Alto 800 Vxi', 'i20 Sportz 1.2', 'Suzuki Alto 800 Lx',
       'Suzuki Vitara Brezza ZDi', 'Suzuki Alto LX', 'Bolero DI',
       'Suzuki Swift Dzire ZDi', 'Scorpio S10 4WD',
       'Suzuki Swift Vdi BSIII', 'Suzuki Wagon R VXi BS III',
       'Suzuki Wagon R VXi Minor', 'Innova 2.0 G 8 STR BS IV',
       'Lodgy 85 PS RXL', 'Yeti Ambition 2.0 TDI CR 4x2',
       'Suzuki Baleno Delta 1.2', 'Duster 110 PS RxZ Diesel Plus',
       'Duster 85 PS RxE Diesel', 'City 1.5 S MT', 'Suzuki Dzire',
       'Amaze', 'Amaze 1.5 SX i DTEC', 'City', 'Redi GO S',
       'Suzuki SX4 ZXI MT', 'Pajero Sport Limited Edition',
       'Suzuki Swift VXi 1.2 ABS BS IV', 'City ZX CVT',
       'Suzuki Wagon R LX BS IV', 'Indigo eCS LS CR4 BS IV',
       'Polo Highline Exquisite P', 'Spark LS 1.0',
       'Duster 110PS Diesel RxZ', 'Cooper S 1.6',
       'Fabia 1.2L Diesel Ambiente', 'Duster', 'Scorpio S4',
       'Scorpio VLX 2WD BS IV', 'Quanto C8', 'EcoSport', 'Brio',
       'Vento Highline Plus 1.5 Diesel AT', 'i20 Magna',
       'Corolla Altis Diesel D4DG', 'Verna Transform SX VTVT',
       'Corolla Altis Petrol Ltd', 'City 1.5 EXi New',
       'Fabia 1.2L Diesel Elegance', '3 Series 320i', 'Suzuki A Star Lxi',
       'Etios GD', 'Figo Diesel EXI Option',
       'Suzuki Swift Dzire VXi 1.2 BS IV', 'Beat LT Diesel',
       '7 Series 740Li Sedan', 'XUV500 W8 AWD 2013', 'i10 Magna 1.2',
       'Verna Fluidic New', 'Suzuki Swift VXi 1.2 BS IV',
       'Suzuki Ertiga ZXI Plus', 'Suzuki Ertiga Vxi', 'Suzuki Ertiga VDi',
       'Suzuki Alto LXi BS III', 'Grand i10 Asta 1.1 CRDi',
       'Amaze 1.2 S i VTEC', 'i20 Asta 1.4 CRDI 6 Speed',
       'Figo Diesel EXI', 'Suzuki Eeco 5 STR WITH AC HTR',
       'Suzuki Ertiga ZXi', 'Suzuki Esteem LXi BS III', 'Suzuki Ritz VXI',
       'Suzuki Ritz LDi', 'Suzuki Dzire VDI', 'Etios Liva G',
       'i20 Sportz 1.4 CRDI', 'Spark', 'Micra XV', 'Suzuki Swift',
       'Amaze 1.5 S i DTEC', 'Beat', 'Corolla', 'City 1.5 V MT',
       'EcoSport Trend 1.5L TDCi', 'i20 Asta 1.2', 'Indica V2 eLS',
       'Motors Ambassador', 'Corolla Altis 1.8 GL', 'Corolla Altis 1.8 J',
       'Innova 2.5 GX BS IV 7 STR', 'Jetta Highline TDI AT',
       'Polo Comfortline 1.2L P', 'Polo', 'Scorpio', 'Sunny', 'Elite i20',
       'Kwid', 'Scorpio VLX Airbag', 'Suzuki Alto 800 Lxi',
       'Spark LT 1.0', 'Redi GO T O', 'Suzuki Swift RS VDI',
       'Punto Emotion 1.2', 'i10 Sportz 1.2', 'Beat LT Opt Diesel',
       'Beat LS Diesel', 'Indigo CS', 'Suzuki Swift VDi', 'Eon Era Plus',
       'XUV500', 'Fiesta', 'Suzuki Wagon R', 'i20',
       'Indigo eCS LX TDI BS III', 'Fluidic Verna 1.6 CRDi SX',
       'Petra ELX 1.2 PS', 'Santro Xing XS', 'Suzuki Ciaz VXi Plus',
       'Suzuki Zen VX', 'Creta 1.6 SX Plus Petrol', 'Scorpio SLX',
       'Innova 2.5 G BS III 8 STR', 'Suzuki Wagon R LXI BS IV',
       'Nano Cx BSIV', 'Suzuki Alto Std BS IV',
       'Suzuki Wagon R LXi BS III', 'Suzuki Swift VXI BSIII',
       'Sumo Victa EX 10 by 7 Str BSIII', 'Passat Diesel Comfortline AT',
       'Scala RxL Diesel Travelogue', 'Grand i10 Sportz O 1.2 Kappa VTVT',
       'i20 Active 1.2 SX', 'Xylo E4', 'Jeep MM 550 XDB',
       'Bolero SLE BS IV', 'Motors  One LX ABS 7 STR', 'Suzuki SX4',
       'Etios', 'City ZX VTEC', 'Suzuki Wagon R LX BS III',
       'City VX O MT Diesel', 'Thar CRDe 4x4 AC',
       'A4 1.8 TFSI Multitronic Premium Plus',
       'Benz GLA Class 200 CDI Sport', 'Rover Freelander 2 SE',
       'Kwid RXT', 'Aria Pleasure 4X2', 'Benz B Class B180 Sports',
       'GO T O', 'Jazz VX MT', 'i20 Active 1.4L SX O', 'Cooper S',
       'Suzuki Ciaz ZXI Plus', 'Tavera Neo', 'Eon Sportz',
       'Sumo Gold Select Variant', 'Suzuki Wagon R 1.0',
       'Suzuki Esteem VXi BS III', 'Enjoy 1.4 LS 8 STR',
       'Suzuki Wagon R 1.0 VXi', 'Terrano XL D Plus',
       'Duster 85 PS RxL Diesel', 'Suzuki Dzire ZXI', 'Kwid RXT Opt',
       'Suzuki  800 Std', 'Kwid 1.0 RXT AMT', 'Scala RxL Diesel',
       'Grand i10 Asta 1.2 Kappa VTVT O', 'Beat LS Petrol', 'Accent GLX',
       'TUV300 T4 Plus', 'Indica V2 Xeta e GLE', 'Indigo CS LS DiCOR',
       'Scorpio VLX Special Edition BS III', 'Accord',
       'EcoSport Titanium 1.5 TDCi', 'Suzuki Ertiga', 'Scorpio 2.6 CRDe',
       'Mobilio', 'Corolla Altis', 'Laura', 'Verna Fluidic',
       'Suzuki Vitara Brezza', 'Manza Aura Quadrajet',
       'Sail UVA Petrol LT ABS', 'Verna Fluidic 1.6 VTVT SX',
       'A4 2.0 TDI 177bhp Premium', 'Elantra SX',
       'Scorpio VLX 4WD Airbag', 'KUV100 K8 D 6 STR', 'Grand i10', 'i10',
       'i20 Active', 'Redi GO', 'Etios Liva', 'Accent', 'Verna',
       'Fortuner', 'i10 Sportz', 'Bolero Power Plus SLE',
       'City 1.5 V MT Exclusive', 'Spark LT 1.0 Airbag',
       'Indigo eCS VX CR4 BS IV', 'Rapid Elegance 1.6 TDI CR MT',
       'Vista Quadrajet VX', 'Suzuki Alto K10 VXi AT',
       'Suzuki Zen LXi BS III', 'Suzuki Swift Dzire Tour LDi',
       'City ZX EXi', 'Beat Diesel', 'Verna 1.4 VTVT',
       'Innova 2.5 E MS 7 STR BS IV', 'Suzuki  800 Std – Befo',
       'Elite i20 Asta 1.4 CRDI', 'Suzuki Versa DX2 8 SEATER BSIII',
       'Indigo LX TDI BS III', 'Vento Konekt Diesel Highline',
       'Benz C Class 200 CDI Classic', 'Santro Xing GLS',
       'Suzuki Omni Limited Edition', 'Sonata Transform 2.4 GDi MT',
       'Elite i20 Sportz 1.2', 'Jazz S MT',
       'Grand i10 Sportz 1.2 Kappa VTVT', 'Suzuki Zen LXi BSII',
       'Scorpio W Turbo 2.6DX 9 Seater', 'Suzuki Alto K10 VXi',
       'Grand i10 Asta 1.2 Kappa VTVT', 'XUV500 W8', 'i20 Magna O 1.2',
       'Duster 85 PS RxL Explore LE', 'Brio V MT', 'TUV300 T8',
       'X Trail Select Variant', 'Ikon 1.3 CLXi NXt Finesse',
       'Fortuner 3.0 4x4 MT', 'Manza ELAN Quadrajet',
       'Benz A Class A 180 Sport Petrol', 'Indigo LS', 'i20 Magna 1.2',
       'Amaze 1.5 E i DTEC', 'Verna 1.6 EX VTVT', '5 Series 520d Sedan',
       'Superb 1.8 TFSI AT', 'Q3 2.0 TDI quattro Premium',
       'Bolero DI BSII', 'Figo Duratorq Diesel Titanium 1.4',
       'Suzuki Wagon R VXI BS IV', 'Logan Diesel 1.5 DLS',
       'Nano GenX XMA', 'City SV', 'Figo Petrol LXI',
       'i10 Magna 1.2 Kappa2', 'Corolla H2',
       'Suzuki Swift Dzire Tour VXi', 'Indigo CS eLS BS IV',
       'Xcent Base 1.1 CRDi', 'Accent Executive Edition',
       'Zest XE 75 PS Diesel', 'Suzuki Dzire LDI', 'Sumo Gold LX BS IV',
       'Corolla Altis GL Petrol', 'Suzuki Eeco 7 STR',
       'Fortuner 3.0 4x2 MT', 'XUV500 W6', 'Tigor Revotron XZ',
       'Suzuki 800', 'Mobilio S i DTEC', 'Verna 1.6 CRDI E',
       'Suzuki Omni Select Variant', 'Indica', 'Santro Xing',
       'Suzuki Zen Estilo', 'Brio VX AT',
       'Suzuki Zen Estilo LXI Green CNG', 'Suzuki Wagon R Select Variant',
       'Nano Lx BSIV', 'XE XE Portfolio', 'Eon Magna Plus',
       'Suzuki Ritz GENUS VXI', 'Grand i10 Magna AT 1.2 Kappa VTVT',
       'Eon D Lite Plus', 'Amaze 1.2 VX i VTEC',
       'Suzuki Estilo VXi ABS BS IV', 'Suzuki Vitara Brezza LDi O',
       'Creta 1.6 SX Plus Petrol AT', 'Scorpio Vlx BSIV',
       'Lancer 1.8 LXi', 'Suzuki  800 AC', 'Suzuki Alto 800 LXI CNG O',
       'Fiesta SXi 1.6 ABS', 'Suzuki Ritz VDi', 'Suzuki Estilo LX BS IV',
       'A6 2.0 TDI Premium', 'Suzuki Alto', 'Suzuki Baleno Sigma 1.2',
       'Verna 1.6 SX VTVT AT', 'Suzuki Swift GLAM', 'Getz Prime 1.3 GVS',
       'Santro', 'Getz Prime 1.3 GLX', 'Beat PS Diesel',
       'EcoSport Trend 1.5 Ti VCT', 'Indica V2 DLG', 'X1 xDrive20d xLine',
       'City 1.5 V AT', 'Nano', 'Cruze LTZ AT', 'Suzuki Swift Dzire VDi',
       'XUV500 W10', 'Suzuki Alto K10 LXi CNG', 'Accent GLE',
       'Motors One SUV', 'Spark 1.0 LT', 'Etios Liva GD',
       'Duster 85PS Diesel RxL Optional with Nav', 'Enjoy',
       '5 Series 530i', 'Cruze LTZ', 'Wrangler Unlimited 4x4 Diesel',
       'Verna VGT CRDi SX ABS', 'Suzuki Omni', 'Suzuki Celerio VDi',
       'Zest Quadrajet 1.3', 'Indigo CS eLX BS IV', 'i10 Era',
       'Indigo eCS LX CR4 BS IV', 'Indigo Marina LS', 'Xcent SX 1.2',
       'Nano LX Special Edition', 'Duster 110 PS RxZ Diesel',
       'Suzuki Wagon R AX BSIV', 'Suzuki Alto K10 New', 'Xylo E8',
       'Manza Aqua Quadrajet', 'Kwid 1.0', 'Venture EX 8 STR',
       'Suzuki Swift Dzire Tour LXi', 'Octavia Classic 1.9 TDI MT',
       'Suzuki Omni LPG BS IV', 'Sumo Gold EX BS IV', 'Verna 1.6 CRDI SX',
       'Scorpio SLX 2.6 Turbo 8 Str', 'Ikon 1.6 Nxt',
       'Innova 2.5 V 7 STR', 'Sunny XL', 'Suzuki Swift VDi BS IV',
       'Innova 2.0 G4', 'Suzuki Swift VDi ABS', 'Elite i20 Asta 1.2',
       'Polo Trendline 1.5L D', 'Etios Liva Diesel',
       'Suzuki Ciaz ZXi Plus RS', 'Elantra 1.8 S',
       'EcoSport Trend 1.5L Ti VCT', 'Indica eV2 LS',
       'XF 2.2 Diesel Luxury', 'Q5 2.0 TDI quattro Premium Plus',
       '3 Series 320d Sedan', 'Suzuki Swift ZXi 1.2 BS IV',
       'X1 sDrive20d', 'Suzuki S Cross Sigma 1.3', 'Suzuki Ertiga LDi',
       'Vento Comfortline Petrol', 'KUV100',
       'Suzuki Swift Dzire Tour VDi', 'Scorpio 2.6 SLX',
       'Suzuki Omni 8 STR BS III', 'Jetta Comfortline 1.9 TDI AT',
       'S80 Summum D4', 'Corolla Altis VL AT Petrol',
       'Pajero Sport 2.5 AT', 'Beat LT Petrol', 'X1',
       'Benz C Class C 220 CDI Avantgarde', 'Vento Comfortline Diesel',
       'Indigo CS GLS', 'Figo Petrol Titanium', 'City ZX GXi',
       'Suzuki Wagon R Duo Lxi', 'Suzuki Zen LX BSII',
       'Duster RxL Petrol', 'Suzuki Baleno Zeta 1.2', 'WR V S MT Petrol',
       'Duster 110 PS RxL Diesel', 'Scorpio LX BS III',
       'Suzuki SX4 Celebration Diesel', 'A3 Cabriolet 40 TFSI',
       'Santro AE GLS Audio', 'Xylo D2 BS IV', 'Getz GLE', 'Creta 1.6 SX',
       'Santro Xing XL AT eRLX Euro III', 'Santro Xing XL eRLX Euro III',
       'Indica V2 DLS BS III', 'City 1.5 E MT', 'Micra XL',
       'City 1.5 S Inspire', 'Indica eV2 eXeta eGLX',
       'Suzuki Omni E 8 STR BS IV', 'Suzuki Swift LDi',
       'Verna 1.6 CRDI SX Plus AT', 'Tavera LS B3 10 Seats BSII',
       'Tiago Revotron XM', 'Tiago Revotorq XZ',
       'Motors Ambassador Classic Mark 4 – Befo',
       'Fusion 1.4 TDCi Diesel', 'Linea Emotion 1.4 L T Jet Petrol',
       'Ikon 1.3 Flair Josh 100', 'Indica V2 LS', 'Xylo D2', 'Eon Magna',
       'Sumo Grande MKII GX', 'Polo Highline1.2L P', 'Tiago Revotron XZ',
       'Indigo eCS', 'Xylo E8 BS IV', 'Sumo Gold FX BSIII', 'Creta',
       'Bolt XM Petrol', 'Suzuki Ritz', 'i20 Asta',
       'Suzuki Swift Select Variant', 'Indica V2 DLX BS III',
       'Scorpio VLX 2.2 mHawk Airbag BSIV', 'Innova 2.5 E 8 STR',
       'KUV100 K8 6 STR', 'Go Plus', 'Endeavor 4x4 Thunder Plus',
       'Indica V2', 'Santro Xing GL', 'Innova 2.5 Z Diesel 7 Seater',
       'Suzuki Alto AX', 'Logan', 'Suzuki 800 Std BS III', 'Sail 1.2 LS',
       'Manza', 'Etios G', 'Qualis', 'Quanto C4', 'Suzuki Swift Dzire',
       'i20 Select Variant', 'City VX Petrol', 'Getz',
       'Benz C Class 200 K MT', 'Fabia', 'Suzuki Ritz VXI ABS',
       'Indica V2 DLE BS III', 'Zest XM Diesel'], dtype=object)

In [42]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 817 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        817 non-null    object
 1   company     817 non-null    object
 2   year        817 non-null    float64
 3   Price       817 non-null    float64
 4   kms_driven  817 non-null    float64
 5   fuel_type   816 non-null    object
dtypes: float64(3), object(3)
memory usage: 77.0+ KB

In [43]:
ds.dropna(inplace=True)

In [44]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 816 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        816 non-null    object
 1   company     816 non-null    object
 2   year        816 non-null    float64
 3   Price       816 non-null    float64
 4   kms_driven  816 non-null    float64
 5   fuel_type   816 non-null    object
dtypes: float64(3), object(3)
memory usage: 44.6+ KB

In [45]:
ds["fuel_type"].unique()

array(['Petrol', 'Diesel', 'LPG'], dtype=object)

In [47]:
ds.duplicated().value_counts()

False    724
True      92
Name: count, dtype: int64

In [48]:
ds.drop_duplicates(inplace=True)

In [49]:
ds.duplicated().value_counts()

False    724
Name: count, dtype: int64

In [50]:
ds["Price"].min()

30000.0

In [51]:
ds["Price"].max()

8500003.0

In [52]:
ds["kms_driven"].min()

0.0

In [53]:
ds["kms_driven"].max()

400000.0

In [59]:
ds[ds["kms_driven"]<100]

,name,company,year,Price,kms_driven,fuel_type
1,Jeep CL550 MDI,Mahindra,2006.0,425000.0,40.0,Diesel
215,Jeep MM 550 XDB,Mahindra,2019.0,390000.0,60.0,Diesel
220,Jeep CL550 MDI,Mahindra,2019.0,379000.0,0.0,Diesel
302,Suzuki Swift VXi 1.2 ABS BS IV,Maruti,2019.0,610000.0,73.0,Petrol
387,Innova 2.5 E MS 7 STR BS IV,Toyota,2012.0,770000.0,0.0,Diesel
470,Suzuki Swift Dzire Tour VXi,Maruti,2011.0,230000.0,65.0,Petrol
702,Figo Petrol Titanium,Ford,2019.0,525000.0,0.0,Petrol
721,Suzuki Zen Estilo LXI Green CNG,Maruti,2009.0,125000.0,0.0,Petrol
738,Creta 1.6 SX,Hyundai,2019.0,1200000.0,0.0,Petrol
762,Tiago Revotorq XZ,Tata,2019.0,568500.0,0.0,Petrol

In [64]:
ds = ds[ds["Price"]<8500000]

In [65]:
ds["Price"].max()

3100000.0

In [74]:
ds = ds[ds["kms_driven"]>500]

In [75]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 709 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        709 non-null    object
 1   company     709 non-null    object
 2   year        709 non-null    float64
 3   Price       709 non-null    float64
 4   kms_driven  709 non-null    float64
 5   fuel_type   709 non-null    object
dtypes: float64(3), object(3)
memory usage: 38.8+ KB

In [77]:
ds.reset_index(drop=True,inplace= True)
ds

,name,company,year,Price,kms_driven,fuel_type
0,Santro Xing XO eRLX Euro III,Hyundai,2007.0,80000.0,45000.0,Petrol
1,Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014.0,325000.0,28000.0,Petrol
2,EcoSport Titanium 1.5L TDCi,Ford,2014.0,575000.0,36000.0,Diesel
3,Figo,Ford,2012.0,175000.0,41000.0,Diesel
4,Eon,Hyundai,2013.0,190000.0,25000.0,Petrol
...,...,...,...,...,...,...
704,Suzuki Ritz VXI ABS,Maruti,2011.0,270000.0,50000.0,Petrol
705,Indica V2 DLE BS III,Tata,2009.0,110000.0,30000.0,Diesel
706,Corolla Altis,Toyota,2009.0,300000.0,132000.0,Petrol
707,Zest XM Diesel,Tata,2018.0,260000.0,27000.0,Diesel
708,Quanto C8,Mahindra,2013.0,390000.0,40000.0,Diesel

In [78]:
ds.to_csv("clean_data.csv")