In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
ds = pd.read_csv("clean_data.csv")
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 709 entries, 0 to 708
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  709 non-null    int64
 1   name        709 non-null    object
 2   company     709 non-null    object
 3   year        709 non-null    float64
 4   Price       709 non-null    float64
 5   kms_driven  709 non-null    float64
 6   fuel_type   709 non-null    object
dtypes: float64(3), int64(1), object(3)
memory usage: 38.9+ KB

In [3]:
ds.columns

Index(['Unnamed: 0', 'name', 'company', 'year', 'Price', 'kms_driven',
       'fuel_type'],
      dtype='object')

In [4]:
X = ds[['name', 'company', 'year', 'kms_driven',
       'fuel_type']]
X

                               name   company    year  kms_driven fuel_type
0      Santro Xing XO eRLX Euro III   Hyundai  2007.0     45000.0    Petrol
1    Grand i10 Magna 1.2 Kappa VTVT   Hyundai  2014.0     28000.0    Petrol
2       EcoSport Titanium 1.5L TDCi      Ford  2014.0     36000.0    Diesel
3                              Figo      Ford  2012.0     41000.0    Diesel
4                               Eon   Hyundai  2013.0     25000.0    Petrol
..                              ...       ...     ...         ...       ...
704             Suzuki Ritz VXI ABS    Maruti  2011.0     50000.0    Petrol
705            Indica V2 DLE BS III      Tata  2009.0     30000.0    Diesel
706                   Corolla Altis    Toyota  2009.0    132000.0    Petrol
707                  Zest XM Diesel      Tata  2018.0     27000.0    Diesel
708                       Quanto C8  Mahindra  2013.0     40000.0    Diesel

[709 rows x 5 columns]

In [5]:
y = ds[['Price']]
y

        Price
0     80000.0
1    325000.0
2    575000.0
3    175000.0
4    190000.0
..        ...
704  270000.0
705  110000.0
706  300000.0
707  260000.0
708  390000.0

[709 rows x 1 columns]

In [6]:
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()

In [7]:
ohe.fit(ds[['name', 'company','fuel_type']])

OneHotEncoder()

In [8]:
ohe.categories_

[array(['3 Series 320d Sedan', '3 Series 320i', '5 Series 520d Sedan',
        '5 Series 530i', '7 Series 740Li Sedan', 'A3 Cabriolet 40 TFSI',
        'A4 1.8 TFSI Multitronic Premium Plus',
        'A4 2.0 TDI 177bhp Premium', 'A6 2.0 TDI Premium', 'A8', 'Accent',
        'Accent Executive Edition', 'Accent GLE', 'Accent GLX', 'Accord',
        'Amaze', 'Amaze 1.2 S i VTEC', 'Amaze 1.2 VX i VTEC',
        'Amaze 1.5 E i DTEC', 'Amaze 1.5 S i DTEC', 'Amaze 1.5 SX i DTEC',
        'Aria Pleasure 4X2', 'Beat', 'Beat Diesel', 'Beat LS Diesel',
        'Beat LS Petrol', 'Beat LT Diesel', 'Beat LT Opt Diesel',
        'Beat LT Petrol', 'Beat PS Diesel',
        'Benz A Class A 180 Sport Petrol', 'Benz B Class B180 Sports',
        'Benz C Class 200 CDI Classic', 'Benz C Class 200 K MT',
        'Benz C Class C 220 CDI Avantgarde',
        'Benz GLA Class 200 CDI Sport', 'Bolero DI', 'Bolero DI BSII',
        'Bolero Power Plus SLE', 'Bolero SLE BS IV', 'Bolt XM Petrol',
        'Brio', 'Brio V MT', 'Brio VX AT', 'City', 'City 1.5 E MT',
        'City 1.5 EXi New', 'City 1.5 S Inspire', 'City 1.5 S MT',
        'City 1.5 V AT', 'City 1.5 V MT', 'City 1.5 V MT Exclusive',
        'City SV', 'City VX O MT Diesel', 'City VX Petrol', 'City ZX CVT',
        'City ZX EXi', 'City ZX GXi', 'City ZX VTEC', 'Cooper S',
        'Cooper S 1.6', 'Corolla', 'Corolla Altis', 'Corolla Altis 1.8 GL',
        'Corolla Altis 1.8 J', 'Corolla Altis Diesel D4DG',
        'Corolla Altis GL Petrol', 'Corolla Altis Petrol Ltd',
        'Corolla Altis VL AT Petrol', 'Corolla H2', 'Creta',
        'Creta 1.6 SX Plus Petrol', 'Creta 1.6 SX Plus Petrol AT',
        'Cruze LTZ', 'Cruze LTZ AT', 'Duster', 'Duster 110 PS RxL Diesel',
        'Duster 110 PS RxZ Diesel', 'Duster 110 PS RxZ Diesel Plus',
        'Duster 110PS Diesel RxZ', 'Duster 85 PS RxE Diesel',
        'Duster 85 PS RxL Diesel', 'Duster 85 PS RxL Explore LE',
        'Duster 85PS Diesel RxL Optional with Nav', 'Duster RxL Petrol',
        'EcoSport', 'EcoSport Ambiente 1.5L TDCi',
        'EcoSport Titanium 1.5 TDCi', 'EcoSport Titanium 1.5L TDCi',
        'EcoSport Trend 1.5 Ti VCT', 'EcoSport Trend 1.5L TDCi',
        'EcoSport Trend 1.5L Ti VCT', 'Elantra 1.8 S', 'Elantra SX',
        'Elite i20', 'Elite i20 Asta 1.2', 'Elite i20 Asta 1.4 CRDI',
        'Elite i20 Magna 1.2', 'Elite i20 Sportz 1.2',
        'Endeavor 4x4 Thunder Plus', 'Enjoy', 'Enjoy 1.4 LS 8 STR', 'Eon',
        'Eon D Lite Plus', 'Eon Era Plus', 'Eon Magna', 'Eon Magna Plus',
        'Eon Sportz', 'Etios', 'Etios G', 'Etios GD', 'Etios Liva',
        'Etios Liva Diesel', 'Etios Liva G', 'Etios Liva GD', 'Fabia',
        'Fabia 1.2L Diesel Ambiente', 'Fabia 1.2L Diesel Elegance',
        'Fabia Classic 1.2 MPI', 'Fiesta', 'Fiesta SXi 1.6 ABS', 'Figo',
        'Figo Diesel EXI', 'Figo Diesel EXI Option',
        'Figo Duratorq Diesel Titanium 1.4', 'Figo Petrol LXI',
        'Fluidic Verna 1.6 CRDi SX', 'Fortuner', 'Fortuner 3.0 4x2 MT',
        'Fortuner 3.0 4x4 MT', 'Fusion 1.4 TDCi Diesel', 'GO T O', 'Getz',
        'Getz GLE', 'Getz Prime 1.3 GLX', 'Getz Prime 1.3 GVS', 'Go Plus',
        'Grand i10', 'Grand i10 Asta 1.1 CRDi',
        'Grand i10 Asta 1.2 Kappa VTVT', 'Grand i10 Asta 1.2 Kappa VTVT O',
        'Grand i10 Magna 1.2 Kappa VTVT',
        'Grand i10 Magna AT 1.2 Kappa VTVT',
        'Grand i10 Sportz 1.2 Kappa VTVT',
        'Grand i10 Sportz O 1.2 Kappa VTVT', 'Ikon 1.3 CLXi NXt Finesse',
        'Ikon 1.3 Flair Josh 100', 'Ikon 1.6 Nxt', 'Indica', 'Indica V2',
        'Indica V2 DLE BS III', 'Indica V2 DLG', 'Indica V2 DLS BS III',
        'Indica V2 DLX BS III', 'Indica V2 LS', 'Indica V2 Xeta e GLE',
        'Indica V2 eLS', 'Indica eV2 LS', 'Indica eV2 eXeta eGLX',
        'Indigo CS', 'Indigo CS GLS', 'Indigo CS LS DiCOR',
        'Indigo CS eLS BS IV', 'Indigo CS eLX BS IV', 'Indigo LS',
        'Indigo LX TDI BS III', 'Indigo Marina LS', 'Indigo eCS',
        'Indigo eCS LS CR4 BS IV', 'Indigo eCS LX CR4 BS IV',
        'Indigo eCS LX TDI BS III', 'Indigo eCS VX CR4 BS IV',
        'Innova 2.0 G 8 STR BS IV', 'Innova 2.0 G4', 'Innova 2.5 E 8 STR',
        'Innova 2.5 G BS III 8 STR', 'Innova 2.5 GX BS IV 7 STR',
        'Innova 2.5 V 7 STR', 'Innova 2.5 Z Diesel 7 Seater', 'Jazz S MT',
        'Jazz VX MT', 'Jeep CL550 MDI', 'Jetta Comfortline 1.9 TDI AT',
        'Jetta Highline TDI AT', 'KUV100', 'KUV100 K8 6 STR',
        'KUV100 K8 D 6 STR', 'Kwid', 'Kwid 1.0', 'Kwid 1.0 RXT AMT',
        'Kwid RXT', 'Kwid RXT Opt', 'Lancer 1.8 LXi', 'Laura',
        'Linea Emotion 1.4 L T Jet Petrol', 'Lodgy 85 PS RXL', 'Logan',
        'Logan Diesel 1.5 DLS', 'Manza', 'Manza Aqua Quadrajet',
        'Manza Aura Quadrajet', 'Manza ELAN Quadrajet', 'Micra XL',
        'Micra XV', 'Mobilio', 'Mobilio S i DTEC',
        'Motors  One LX ABS 7 STR', 'Motors Ambassador',
        'Motors Ambassador Classic Mark 4 – Befo', 'Motors One SUV',
        'Nano', 'Nano Cx BSIV', 'Nano GenX XMA', 'Nano LX Special Edition',
        'Nano Lx BSIV', 'Octavia Classic 1.9 TDI MT',
        'Pajero Sport 2.5 AT', 'Pajero Sport Limited Edition',
        'Passat Diesel Comfortline AT', 'Petra ELX 1.2 PS', 'Polo',
        'Polo Comfortline 1.2L P', 'Polo Highline Exquisite P',
        'Polo Highline1.2L P', 'Polo Trendline 1.5L D',
        'Punto Emotion 1.2', 'Q3 2.0 TDI quattro Premium',
        'Q5 2.0 TDI quattro Premium Plus', 'Q7', 'Qualis', 'Quanto C4',
        'Quanto C8', 'Rapid Elegance 1.6 TDI CR MT', 'Redi GO',
        'Redi GO S', 'Redi GO T O', 'Rover Freelander 2 SE',
        'S80 Summum D4', 'Sail 1.2 LS', 'Sail UVA Petrol LT ABS', 'Santro',
        'Santro AE GLS Audio', 'Santro Xing', 'Santro Xing GL',
        'Santro Xing GLS', 'Santro Xing XL AT eRLX Euro III',
        'Santro Xing XL eRLX Euro III', 'Santro Xing XO eRLX Euro III',
        'Santro Xing XS', 'Scala RxL Diesel',
        'Scala RxL Diesel Travelogue', 'Scorpio', 'Scorpio 2.6 CRDe',
        'Scorpio 2.6 SLX', 'Scorpio LX BS III', 'Scorpio S10',
        'Scorpio S10 4WD', 'Scorpio S4', 'Scorpio SLE BS IV',
        'Scorpio SLX', 'Scorpio SLX 2.6 Turbo 8 Str',
        'Scorpio VLX 2.2 mHawk Airbag BSIV', 'Scorpio VLX 2WD BS IV',
        'Scorpio VLX 4WD Airbag', 'Scorpio VLX Airbag',
        'Scorpio VLX Special Edition BS III', 'Scorpio Vlx BSIV',
        'Scorpio W Turbo 2.6DX 9 Seater', 'Sonata Transform 2.4 GDi MT',
        'Spark', 'Spark 1.0 LT', 'Spark LS 1.0', 'Spark LT 1.0',
        'Spark LT 1.0 Airbag', 'Sumo Gold EX BS IV', 'Sumo Gold FX BSIII',
        'Sumo Gold LX BS IV', 'Sumo Gold Select Variant',
        'Sumo Grande MKII GX', 'Sumo Victa EX 10 by 7 Str BSIII', 'Sunny',
        'Sunny XL', 'Superb 1.8 TFSI AT', 'Suzuki  800 AC',
        'Suzuki  800 Std', 'Suzuki  800 Std – Befo', 'Suzuki 800',
        'Suzuki 800 Std BS III', 'Suzuki A Star Lxi', 'Suzuki Alto',
        'Suzuki Alto 800', 'Suzuki Alto 800 LXI CNG O',
        'Suzuki Alto 800 Lx', 'Suzuki Alto 800 Lxi', 'Suzuki Alto 800 Vxi',
        'Suzuki Alto AX', 'Suzuki Alto K10 LXi CNG', 'Suzuki Alto K10 New',
        'Suzuki Alto K10 VXi', 'Suzuki Alto K10 VXi AMT',
        'Suzuki Alto K10 VXi AT', 'Suzuki Alto LX',
        'Suzuki Alto LXi BS III', 'Suzuki Alto Std BS IV',
        'Suzuki Baleno Delta 1.2', 'Suzuki Baleno Sigma 1.2',
        'Suzuki Baleno Zeta 1.2', 'Suzuki Celerio VDi',
        'Suzuki Ciaz VXi Plus', 'Suzuki Ciaz ZXI Plus',
        'Suzuki Ciaz ZXi Plus RS', 'Suzuki Dzire', 'Suzuki Dzire LDI',
        'Suzuki Dzire VDI', 'Suzuki Dzire ZXI',
        'Suzuki Eeco 5 STR WITH AC HTR', 'Suzuki Eeco 7 STR',
        'Suzuki Ertiga', 'Suzuki Ertiga LDi', 'Suzuki Ertiga VDi',
        'Suzuki Ertiga Vxi', 'Suzuki Ertiga ZXI Plus', 'Suzuki Ertiga ZXi',
        'Suzuki Esteem LXi BS III', 'Suzuki Esteem VXi BS III',
        'Suzuki Estilo LX BS IV', 'Suzuki Estilo VXi ABS BS IV',
        'Suzuki Omni', 'Suzuki Omni 8 STR BS III',
        'Suzuki Omni E 8 STR BS IV', 'Suzuki Omni LPG BS IV',
        'Suzuki Omni Limited Edition', 'Suzuki Omni Select Variant',
        'Suzuki Ritz', 'Suzuki Ritz GENUS VXI', 'Suzuki Ritz LDi',
        'Suzuki Ritz VDi', 'Suzuki Ritz VXI', 'Suzuki Ritz VXI ABS',
        'Suzuki S Cross Sigma 1.3', 'Suzuki SX4',
        'Suzuki SX4 Celebration Diesel', 'Suzuki SX4 ZXI MT',
        'Suzuki Stingray VXi', 'Suzuki Swift', 'Suzuki Swift Dzire',
        'Suzuki Swift Dzire Tour LDi', 'Suzuki Swift Dzire Tour LXi',
        'Suzuki Swift Dzire Tour VDi', 'Suzuki Swift Dzire VDi',
        'Suzuki Swift Dzire VXi 1.2 BS IV', 'Suzuki Swift Dzire ZDi',
        'Suzuki Swift GLAM', 'Suzuki Swift LDi', 'Suzuki Swift RS VDI',
        'Suzuki Swift Select Variant', 'Suzuki Swift VDi',
        'Suzuki Swift VDi ABS', 'Suzuki Swift VDi BS IV',
        'Suzuki Swift VXI BSIII', 'Suzuki Swift VXi 1.2 ABS BS IV',
        'Suzuki Swift VXi 1.2 BS IV', 'Suzuki Swift Vdi BSIII',
        'Suzuki Swift ZXi 1.2 BS IV', 'Suzuki Versa DX2 8 SEATER BSIII',
        'Suzuki Vitara Brezza', 'Suzuki Vitara Brezza LDi O',
        'Suzuki Vitara Brezza ZDi', 'Suzuki Wagon R', 'Suzuki Wagon R 1.0',
        'Suzuki Wagon R 1.0 VXi', 'Suzuki Wagon R AX BSIV',
        'Suzuki Wagon R Duo Lxi', 'Suzuki Wagon R LX BS III',
        'Suzuki Wagon R LX BS IV', 'Suzuki Wagon R LXI BS IV',
        'Suzuki Wagon R LXi BS III', 'Suzuki Wagon R Select Variant',
        'Suzuki Wagon R VXI BS IV', 'Suzuki Wagon R VXi BS III',
        'Suzuki Wagon R VXi Minor', 'Suzuki Zen Estilo',
        'Suzuki Zen Estilo LXI Green CNG', 'Suzuki Zen LX BSII',
        'Suzuki Zen LXi BS III', 'Suzuki Zen LXi BSII', 'Suzuki Zen VX',
        'TUV300 T4 Plus', 'TUV300 T8', 'Tavera LS B3 10 Seats BSII',
        'Tavera Neo', 'Terrano XL D Plus', 'Thar CRDe 4x4 AC',
        'Tiago Revotron XM', 'Tiago Revotron XZ',
        'Vento Comfortline Diesel', 'Vento Comfortline Petrol',
        'Vento Highline Plus 1.5 Diesel AT',
        'Vento Konekt Diesel Highline', 'Venture EX 8 STR', 'Verna',
        'Verna 1.4 VTVT', 'Verna 1.6 CRDI E', 'Verna 1.6 CRDI SX',
        'Verna 1.6 CRDI SX Plus AT', 'Verna 1.6 EX VTVT',
        'Verna 1.6 SX VTVT AT', 'Verna Fluidic',
        'Verna Fluidic 1.6 VTVT SX', 'Verna Fluidic New',
        'Verna Transform SX VTVT', 'Verna VGT CRDi SX ABS',
        'Vista Quadrajet VX', 'WR V S MT Petrol',
        'Wrangler Unlimited 4x4 Diesel', 'X1', 'X1 sDrive20d',
        'X1 xDrive20d xLine', 'XE XE Portfolio', 'XF 2.2 Diesel Luxury',
        'XUV500', 'XUV500 W10', 'XUV500 W6', 'XUV500 W8',
        'XUV500 W8 AWD 2013', 'Xcent Base 1.1 CRDi', 'Xcent SX 1.2',
        'Xylo D2', 'Xylo D2 BS IV', 'Xylo E4', 'Xylo E8', 'Xylo E8 BS IV',
        'Yeti Ambition 2.0 TDI CR 4x2', 'Zest Quadrajet 1.3',
        'Zest XE 75 PS Diesel', 'Zest XM Diesel', 'i10', 'i10 Era',
        'i10 Magna 1.2', 'i10 Magna 1.2 Kappa2', 'i10 Sportz',
        'i10 Sportz 1.2', 'i20', 'i20 Active', 'i20 Active 1.2 SX',
        'i20 Active 1.4L SX O', 'i20 Asta', 'i20 Asta 1.2',
        'i20 Asta 1.4 CRDI 6 Speed', 'i20 Magna', 'i20 Magna 1.2',
        'i20 Magna O 1.2', 'i20 Select Variant', 'i20 Sportz 1.2',
        'i20 Sportz 1.4 CRDI'], dtype=object),
 array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
        'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
        'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
        'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
       dtype=object),
 array(['Diesel', 'LPG', 'Petrol'], dtype=object)]

In [9]:
ct =make_column_transformer((OneHotEncoder(categories=ohe.categories_),["name","company","fuel_type"]),remainder="passthrough")
ct

ColumnTransformer(remainder='passthrough',
                  transformers=[('onehotencoder',
                                 OneHotEncoder(categories=[array(['3 Series 320d Sedan', '3 Series 320i', '5 Series 520d Sedan',
       '5 Series 530i', '7 Series 740Li Sedan', 'A3 Cabriolet 40 TFSI',
       'A4 1.8 TFSI Multitronic Premium Plus',
       'A4 2.0 TDI 177bhp Premium', 'A6 2.0 TDI Premium', 'A8', 'Accent',
       'Accent Executive Edition', 'Accent GLE', 'Accent GLX'...
       'i20 Sportz 1.4 CRDI'], dtype=object),
                                                           array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
       'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
       'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
       'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
      dtype=object),
                                                           array(['Diesel', 'LPG', 'Petrol'], dtype=object)]),
                                 ['name', 'company', 'fuel_type'])])

In [10]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()

In [11]:
from sklearn.pipeline import make_pipeline

In [12]:
pipe = make_pipeline(ct,reg)
pipe

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['3 Series 320d Sedan', '3 Series 320i', '5 Series 520d Sedan',
       '5 Series 530i', '7 Series 740Li Sedan', 'A3 Cabriolet 40 TFSI',
       'A4 1.8 TFSI Multitronic Premium Plus',
       'A4 2.0 TDI 177bhp Premium', 'A6 2.0 TDI Premium', 'A8', 'Accent',
       'Accent Exec...
                                                                            array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
       'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
       'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
       'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
      dtype=object),
                                                                            array(['Diesel', 'LPG', 'Petrol'], dtype=object)]),
                                                  ['name', 'company',
                                                   'fuel_type'])])),
                ('linearregression', LinearRegression())])

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.1,random_state=0)

In [14]:
y_train

        Price
485  315000.0
122  474999.0
375  190000.0
573  320000.0
706  300000.0
..        ...
359  165000.0
192  450000.0
629  160000.0
559  200000.0
684  265000.0

[638 rows x 1 columns]

In [15]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['3 Series 320d Sedan', '3 Series 320i', '5 Series 520d Sedan',
       '5 Series 530i', '7 Series 740Li Sedan', 'A3 Cabriolet 40 TFSI',
       'A4 1.8 TFSI Multitronic Premium Plus',
       'A4 2.0 TDI 177bhp Premium', 'A6 2.0 TDI Premium', 'A8', 'Accent',
       'Accent Exec...
                                                                            array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
       'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
       'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
       'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
      dtype=object),
                                                                            array(['Diesel', 'LPG', 'Petrol'], dtype=object)]),
                                                  ['name', 'company',
                                                   'fuel_type'])])),
                ('linearregression', LinearRegression())])

In [31]:
data = pd.DataFrame(data = [["Figo","Ford",2017,25000,"Petrol"]],columns=['name', 'company', 'year', 'kms_driven',
       'fuel_type'])
data

# myinput = pd.DataFrame(data=[["Ford","Figo",2015,50000,"Diesel"]],columns=["company","name","year","kms_driven","fuel_type"])

   name company  year  kms_driven fuel_type
0  Figo    Ford  2017       25000    Petrol

In [32]:
pipe.predict(data)

array([[504031.50127783]])

In [22]:
X_test

                                 name    company    year  kms_driven fuel_type
540                         XUV500 W8   Mahindra  2015.0     28600.0    Diesel
467                    Eon Magna Plus    Hyundai  2013.0     23000.0    Petrol
355              i10 Magna 1.2 Kappa2    Hyundai  2008.0    100200.0    Petrol
172                           Xylo E4   Mahindra  2012.0     35000.0    Diesel
637                  Suzuki Swift VDi     Maruti  2009.0     90000.0    Diesel
..                                ...        ...     ...         ...       ...
500                    Beat LT Diesel  Chevrolet  2012.0     90001.0    Diesel
187                          Kwid RXT    Renault  2017.0      5000.0    Petrol
293  Suzuki Swift Dzire VXi 1.2 BS IV     Maruti  2012.0     40000.0    Petrol
142                            XUV500   Mahindra  2014.0     52000.0    Diesel
310               Suzuki Alto K10 VXi     Maruti  2014.0     22000.0    Petrol

[71 rows x 5 columns]

In [25]:
y_pred = pipe.predict(X_test)
y_pred

array([[ 6.56279228e+05],
       [ 2.68205552e+05],
       [ 1.47750000e+05],
       [ 4.78305461e+05],
       [ 1.62925819e+05],
       [ 4.94850509e+05],
       [ 4.83121065e+05],
       [ 1.26267788e+06],
       [ 3.36721456e+05],
       [ 4.86149854e+05],
       [ 5.54675103e+05],
       [ 2.75414168e+05],
       [ 3.79788829e+05],
       [ 6.10938024e+05],
       [ 2.67719879e+05],
       [ 2.13498270e+05],
       [ 3.66820989e+05],
       [ 2.57896084e+05],
       [-8.30502755e+02],
       [ 3.80826839e+05],
       [ 2.94551775e+05],
       [ 4.07684813e+05],
       [ 3.48138556e+05],
       [ 4.71217500e+05],
       [ 3.76296916e+05],
       [ 2.81150168e+05],
       [ 3.57548627e+05],
       [ 1.45176648e+06],
       [ 4.13795128e+05],
       [ 3.43789432e+05],
       [ 4.29860060e+05],
       [-5.04272487e+04],
       [ 4.52002988e+05],
       [ 3.31854027e+05],
       [ 1.17539693e+06],
       [ 4.07006010e+05],
       [ 3.09855854e+05],
       [ 3.84903192e+05],
       [ 5.05614393e+05],
       [ 6.32563391e+05],
       [ 3.03266317e+05],
       [ 4.41643405e+05],
       [ 9.62393203e+04],
       [ 2.67845732e+05],
       [ 3.78217567e+05],
       [ 4.86893101e+05],
       [ 2.87946894e+05],
       [ 7.61640017e+03],
       [ 2.25975185e+05],
       [ 4.25129960e+05],
       [ 5.09394515e+05],
       [ 2.26050479e+05],
       [-1.19892399e+05],
       [ 3.27945180e+05],
       [ 5.18060816e+05],
       [ 1.57448178e+06],
       [ 4.13476397e+05],
       [ 2.81515641e+05],
       [ 4.89917790e+05],
       [ 4.24086520e+05],
       [ 4.32907077e+05],
       [ 3.71596648e+04],
       [ 7.11438057e+05],
       [ 2.19272231e+05],
       [ 3.67605643e+05],
       [ 1.90488250e+05],
       [ 1.19510851e+05],
       [ 3.64506178e+05],
       [ 2.79233486e+05],
       [ 6.54857253e+05],
       [ 3.07669595e+05]])

In [26]:
y_pred = pd.DataFrame(data = y_pred,columns=["Result"])
y_pred

           Result
0   656279.228117
1   268205.551902
2   147750.000065
3   478305.460993
4   162925.819019
..            ...
66  119510.850799
67  364506.178068
68  279233.486142
69  654857.253371
70  307669.595009

[71 rows x 1 columns]

In [27]:
y_test

        Price
540  900000.0
467  185000.0
355  275000.0
172  400000.0
637  120000.0
..        ...
500  130000.0
187  340000.0
293  225000.0
142  699999.0
310  270000.0

[71 rows x 1 columns]

In [28]:
result  = pd.concat([y_test.reset_index(drop=True),y_pred.reset_index(drop=True)],axis=1)
result

       Price         Result
0   900000.0  656279.228117
1   185000.0  268205.551902
2   275000.0  147750.000065
3   400000.0  478305.460993
4   120000.0  162925.819019
..       ...            ...
66  130000.0  119510.850799
67  340000.0  364506.178068
68  225000.0  279233.486142
69  699999.0  654857.253371
70  270000.0  307669.595009

[71 rows x 2 columns]

In [30]:
from sklearn.metrics import r2_score
score = r2_score(result['Price'],result['Result'])
print(score)

0.6674120134585697

In [38]:
new_array = []
for i in range(0,101):
    X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.1,random_state=i)
    pipe.fit(X_train,y_train)
    y_pred = pipe.predict(X_test)
    y_pred
    y_pred = pd.DataFrame(data = y_pred,columns=["Result"])
    y_pred
    result  = pd.concat([y_test.reset_index(drop=True),y_pred.reset_index(drop=True)],axis=1)
    result
    score = r2_score(result['Price'],result['Result'])
    new_array.append(score)

AttributeError: 'list' object has no attribute 'max'

In [41]:
new_array = np.array(new_array)
new_array.max()

np.float64(0.8048211945211248)

In [42]:
new_array.argmax()

np.int64(49)

In [44]:
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.1,random_state=49)
pipe.fit(X_train,y_train)
y_pred = pipe.predict(X_test)
y_pred
y_pred = pd.DataFrame(data = y_pred,columns=["Result"])
y_pred
result  = pd.concat([y_test.reset_index(drop=True),y_pred.reset_index(drop=True)],axis=1)
result
score = r2_score(result['Price'],result['Result'])
score

0.8048211945211248

In [45]:
import pickle as pkl
pkl.dump(pipe,open("CPP.pkl","wb+"))